### ISSUE TITLE
Will you enhance the parser of 'show inventory' to support C8300 platform.

### ISSUE THREAD

**Issue by vskyman** [CiscoTestAutomation/genieparser#106]
[2020-03-18 12:32:43,607] +++ Thallium-03: executing command 'show inventory' +++
show inventory

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO: Please use "show license UDI" to get serial number for licensing.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

NAME: "Chassis", DESCR: "Cisco isr9000 Series Chassis"
PID: C8300-1N1S-6G     , VID: V00  , SN: FDO2319A1RM

NAME: "Fan Tray", DESCR: "Cisco C8300 1RU Fan Assembly"
PID: C8300-FAN-1R      , VID:      , SN:            

NAME: "module 0", DESCR: "Cisco isr9000 series Unknown Module"
PID: C8300-1N1S-6G     , VID:      , SN:            

NAME: "NIM subslot 0/0", DESCR: "Front Panel 6 ports Gigabitethernet Module"
PID: 4x1G-2xSFP        , VID: V01  , SN:            

NAME: "module 1", DESCR: "Cisco C-SM-NIM-ADPT SM to NIM adapter"
PID: C-SM-NIM-ADPT     , VID: V01  , SN: FDO23370TB8

NAME: "NIM subslot 1/0", DESCR: "NIM-8MFT-T1/E1 - T1/E1 Serial Module"
PID: NIM-8MFT-T1/E1    , VID: V04  , SN: FOC21032R9L

NAME: "module R0", DESCR: "Cisco isr9000 Series Route Processor"
PID: C8300-1N1S-6G     , VID: V00  , SN: FDO231403QN

NAME: "module F0", DESCR: "Cisco isr9000 Series Forwarding Processor"
PID: C8300-1N1S-6G     , VID:      , SN:            

Thallium-03#
[2020-03-18 12:32:44,950] ERROR in app: Exception on /pyatsRestService/v1/getDeviceInventoryInfo [POST]
Traceback (most recent call last):
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/flask_restplus/marshalling.py", line 243, in wrapper
    resp = f(*args, **kwargs)
  File "./apis/ns_pyatsRestService.py", line 1340, in post
    showInventoryOutput = device.parse(DEVICE_SHOW_INVENTORY_COMMAND, alias=connect_alias)
  File "src/genie/conf/base/device.py", line 517, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/zhonman/task/python3_dir/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_platform.py", line 1942, in cli
    subslot_dict = lc_dict.setdefault('subslot', {}).\
UnboundLocalError: local variable 'lc_dict' referenced before assignment

**Comment by vskyman** [comment]
The issue is that the prefix 'C8300' of the PID is not acknowledged as the lc type.

**Comment by xiaoxinz-cisco** [comment]
Hello @vskyman ,

Thank you for reporting. We will look into the issue and get back to you.

Thanks,
Irene

**Comment by kamyarz1991** [comment]
"C-SM-NIM-ADPT" Where do you expect this to see: under rp or lc or other?

**Comment by vskyman** [comment]
> "C-SM-NIM-ADPT" Where do you expect this to see: under rp or lc or other?

I think it should be lc, 
and could we map "module \d+"  to 'lc' and map "module R\d+" to 'rp'  and so on,
I think it may be more compatible that sets the slot type by parsing the 'Name' other than 'PID'

**Comment by xiaoxinz-cisco** [comment]
Hello @vskyman 

We fixed the issue and genieparser package **20.2.1b4** has been released with the fix.
Could you please run the following command and try again to see if it works?

**pip install genie.libs.parser --upgrade --pre**

Please try and let's know if there is an issue.

Thanks,
Irene
