### ISSUE TITLE
Typo in the function

### ISSUE THREAD

**Issue by VitMain** [CiscoTestAutomation/genieparser#134]
https://github.com/CiscoTestAutomation/genieparser/blob/feca99a851cf737cd4adda5048c1f52667a3d76c/src/genie/libs/parser/iosxe/show_acl.py#L529

**Comment by VitMain** [comment]
`Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 343, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/Users/VitMain/Work/filters/lib/python3.7/site-packages/genie/libs/ops/acl/iosxe/acl.py", line 93, in learn
    self.make(final_call=True)
  File "/Users/VitMain/Work/filters/lib/python3.7/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/VitMain/Work/filters/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_acl.py", line 529, in cli
    options_name = re.sealrch('options +(\w+)', left).groups()[0]
AttributeError: module 're' has no attribute 'sealrch'`

**Comment by VitMain** [comment]
```Python
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 343, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/Users/VitMain/Work/filters/lib/python3.7/site-packages/genie/libs/ops/acl/iosxe/acl.py", line 93, in learn
    self.make(final_call=True)
  File "/Users/VitMain/Work/filters/lib/python3.7/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/VitMain/Work/filters/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_acl.py", line 529, in cli
    options_name = re.sealrch('options +(\w+)', left).groups()[0]
AttributeError: module 're' has no attribute 'sealrch'

```

**Comment by IreneZhou0129** [comment]
Hi @VitMain ,

Thanks for pointing out. Could you please fix it and create a pull request here? Our team will review and merge your contribution.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @VitMain ,

Thanks for pointing out. Could you please fix it and create a pull request here? Our team will review and merge your contribution.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @VitMain ,

Just for your information, the pull request #144 includes this typo fix.

Thanks,
Irene

**Comment by xiaoxinz-cisco** [comment]
Hi @VitMain ,

The #144 is merged. Thanks again for noticing the mistake in our code! 

Thanks,
Irene
