### ISSUE TITLE
No parsing schema validation when executing dev.parse(command_to_parse, output="output_to_parse") and dev not connected

### ISSUE THREAD

**Issue by salvapinyol** [CiscoTestAutomation/genieparser#136]
Hi:

I've attached a demo script to show the issue (genie_parse_validation.py.txt);

If I run the script as it is I get the following exception:

Traceback (most recent call last):
  File "/var/backups/pipenvs/py3network_scripts/src/genie_scripts/genie_parse_validation.py", line 36, in <module>
    parsed_output = dev.parse("show cdp neighbors", output=raw_output)
  File "src/genie/conf/base/device.py", line 552, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 581, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 405, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['cdp', 'index', 2, 'local_interface'], ['cdp', 'index', 2, 'hold_time'], ['cdp', 'index', 2, 'port_id']]

That is fine because the current parser can't parse the provided output.

If I comment line 24 ( dev.connect(log_stdout=True) and run the script again, I don't get any exception and the raw_output string is parsed, but the parsed result is incomplete. 
This is the incomplete result returned by dev.parse:

{'cdp': {'index': {1: {'capability': 'S',
                       'device_id': 'AXCISCN4.cosmos.es.ftgroup',
                       'hold_time': 153,
                       'local_interface': 'GigabitEthernet0/1',
                       'platform': 'WS-C2960-',
                       'port_id': 'GigabitEthernet0/1'},
                   2: {'device_id': 'AXCIRPE2.net.orange.es'}}}}

This behavior makes genie parsing not working as expected in netmiko for instance (I suspect the same happens in ansible, but not tested)

Salva.

[genie_parse_validation.py.txt](https://github.com/CiscoTestAutomation/genieparser/files/4574878/genie_parse_validation.py.txt)

**Comment by tahigash** [comment]
@salvapinyol We've fixed the issue and released v20.5 yesterday.
please upgrade to v20.5 and check.

upgrade:
```
pyats version update

**Comment by salvapinyol** [comment]
@tahigash great!. I've tested and now it works as expected!. Thanks!
