### ISSUE TITLE
iosxe 'show policy-map interface <int> input/output' - top_level_dict' referenced before assignment

### ISSUE THREAD

**Issue by oianson** [CiscoTestAutomation/genieparser#174]
I'm using an iosxe device and trying to parse the following command: show policy-map interface CUST123-PIN-T5/0/0.20 input using Robot Framework Genie (20.5) library `parse "show policy-map interface CUST123-PIN-T5/0/0.20 input" on device "Router"`

I am getting the following error :
```
UnboundLocalError: local variable 'top_level_dict' referenced before assignment 
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/genie/libs/robot/GenieRobot.py", line 115, in metaparser_on_device
    parser=parser)
  File "/venv/lib/python3.7/site-packages/genie/libs/robot/GenieRobot.py", line 154, in metaparser_on_device_alias_context
    return con.parse(parser)
  File "src/genie/conf/base/device.py", line 552, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 579, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/venv/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 1333, in cli
    return super().cli(output=show_output, interface=interface, class_name=class_name)
  File "/venv/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 663, in cli
    service_policy_dict = top_level_dict.setdefault('service_policy', {}).\
```

The 'output' version of the command also gives the same error.

**Comment by LenzDong** [comment]
Hi,
Thank you for reporting the issue.
We will provide a fix and let you know when it's ready.

Thanks

**Comment by LenzDong** [comment]
Hi,

The parser fix is released. Please upgrade genie.libs.parser to the latest v20.6

Thanks

**Comment by oianson** [comment]
Thank you @LenzDong !
