### ISSUE TITLE
Issue with pyats "show policy-map interface"  on Cat9K

### ISSUE THREAD

**Issue by wimdepauw** [CiscoTestAutomation/genieparser#201]
wim@ubuntu:~/pyats/pyats-ios-sample/cat9k$ more cat9k_sho-policy-map-interface_exception.txt
Issue with the parser sho policy-map interface

Traceback (most recent call last):
Hi,
When I perform the following command pyats parse "sho policy-map interface" --testbed testbed.yaml --output cat9k I'm receiving the following error message.
I'm running pyats v20.6

 File "src/genie/cli/commands/parser.py", line 293, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 552, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 579, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/wim/.local/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 1306, in cli
    return super().cli(output=show_output)
  File "/home/wim/.local/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 753, in cli
    match_list.append(m.groupdict()['match'].lstrip())
UnboundLocalError: local variable 'match_list' referenced before assignment

wim@ubuntu:~/pyats/pyats-ios-sample$ pyats version check
You are currently running pyATS version: 20.6
Python: 3.6.9 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        20.6.1 
  genie.libs.clean             20.6.1 
  genie.libs.conf              20.6   
  genie.libs.filetransferutils 20.6   
  genie.libs.ops               20.6   
  genie.libs.parser            20.6.1 
  genie.libs.robot             20.6   
  genie.libs.sdk               20.6.1 
  genie.telemetry              20.6   
  genie.trafficgen             20.6   
  pyats                        20.6   
  pyats.aereport               20.6   
  pyats.aetest                 20.6   
  pyats.async                  20.6   
  pyats.connections            20.6   
  pyats.contrib                20.6.1 
  pyats.datastructures         20.6   
  pyats.easypy                 20.6.1 
  pyats.kleenex                20.6   
  pyats.log                    20.6.1 
  pyats.reporter               20.6   
  pyats.results                20.6   
  pyats.robot                  20.6   
  pyats.tcl                    20.6   
  pyats.topology               20.6   
  pyats.utils                  20.6   
  unicon                       20.6   
  unicon.plugins               20.6   

Do you know how we could fix this problem ?

**Comment by tahigash** [comment]
Hi @wimdepauw , could you please upgrade pyats by below command to see if there is still issue with latest package?

```
pyats version update
```

if the same issue exists, please send the actual output from the show command with the error to pyats-support-ext@cisco.com

**Comment by tahigash** [comment]
No response for a while. so closing the issue. please feel free to reopen when needed again.

**Comment by wimdepauw** [comment]
Hi, 
Sorry for the late response but  I was on holiday. I've upgraded the pyats to version 20.8 but I'm still getting the same error message.
(pyats) wim@ubuntu:~/pyats/pyats-ios-sample$ pyats parse "show policy-map" --testbed testbed_devnet.yaml 
  0%|                                                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]Issue with the parser show policy-map


Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 301, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/wim/pyats/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 1796, in cli
    conform_list.append(m.groupdict()['conform_action'])
UnboundLocalError: local variable 'conform_list' referenced before assignment
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.06s/it]

(pyats) wim@ubuntu:~/pyats/pyats-ios-sample$ pyats parse "show policy-map interface gi3" --testbed testbed_devnet.yaml 
  0%|                                                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]Issue with the parser show policy-map interface gi3


Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 301, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/wim/pyats/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 1306, in cli
    return super().cli(output=show_output)
  File "/home/wim/pyats/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_policy_map.py", line 720, in cli
    class_map_dict['packets'] = int(packets)
UnboundLocalError: local variable 'class_map_dict' referenced before assignment
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.57s/it]

(pyats) wim@ubuntu:~/pyats/pyats-ios-sample
I will send the detailed output to the  listed email address.
gr
wim

**Comment by tahigash** [comment]
thanks for the update and sending the log via email. Reopened the issue. and I will be looking into the log and get back to you.

**Comment by tahigash** [comment]
provided beta package with fix via email. closing this issue
