### ISSUE TITLE
NXOS 'show interface status' parsing error when NVE interfaces exist

### ISSUE THREAD

**Issue by jamiecaesar** [CiscoTestAutomation/genieparser#242]
The `show interface status` parser for NXOS works fine unless there is an NVE interface in the output, and then a SchemaMissingKeyError exception is thrown.  If I manually remove the line from the output that contains the `nve1` interface, then the output is successfully parsed, but when the `nve1` interface is in the output, the full traceback is:

```
Traceback (most recent call last):
  File "test_parse.py", line 140, in <module>
    parsed_output = device.parse(cmd, output=raw_cli_output)
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 584, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['interfaces', 'Nve1', 'vlan']]
```

Below is the full content of the `test_parse.py` script referenced in the above traceback.

```
raw_cli_output = """
--------------------------------------------------------------------------------
Port          Name               Status    Vlan      Duplex  Speed   Type
--------------------------------------------------------------------------------
mgmt0         --                 notconnec routed    auto    auto    --        
 
--------------------------------------------------------------------------------
Port          Name               Status    Vlan      Duplex  Speed   Type
--------------------------------------------------------------------------------
Eth1/1        --                 notconnec 1         auto    auto    10g       
Eth1/2        --                 notconnec 1         auto    auto    10g       
Eth1/3        --                 notconnec 1         auto    auto    10g       
Eth1/4        --                 notconnec 1         auto    auto    10g       
Eth1/5        --                 notconnec 1         auto    auto    10g       
Eth1/6        --                 notconnec 1         auto    auto    10g       
Eth1/7        --                 notconnec 1         auto    auto    10g       
Eth1/8        --                 notconnec 1         auto    auto    10g       
Eth1/9        --                 notconnec 1         auto    auto    10g        
Eth1/10       free-copper-port   disabled  1         auto    auto    10g       
Eth1/11       --                 notconnec 1         auto    auto    10g       
Eth1/12       --                 notconnec 1         auto    auto    10g       
Eth1/13       --                 notconnec 1         auto    auto    10g       
Eth1/14       --                 notconnec 1         auto    auto    10g       
Eth1/15       --                 notconnec 1         auto    auto    10g       
Eth1/16       --                 notconnec 1         auto    auto    10g       
Eth1/17       --                 notconnec 1         auto    auto    10g       
Eth1/18       --                 notconnec 1         auto    auto    10g       
Eth1/19       --                 notconnec 1         auto    auto    10g       
Eth1/20       mytest             notconnec 1         auto    auto    10g       
Eth1/21       --                 notconnec 1         auto    auto    10g       
Eth1/22       --                 notconnec 1         auto    auto    10g       
Eth1/23       --                 notconnec 1         auto    auto    10g       
Eth1/24       --                 notconnec 1         auto    auto    10g       
Eth1/25       --                 notconnec 1         auto    auto    10g       
Eth1/26       --                 notconnec 1         auto    auto    10g       
Eth1/27       --                 notconnec 1         auto    auto    10g       
Eth1/28       --                 notconnec 1         auto    auto    10g       
Eth1/29       --                 notconnec 1         auto    auto    10g       
Eth1/30       --                 notconnec 1         auto    auto    10g       
Eth1/31       --                 notconnec 501       auto    auto    10g       
Eth1/32       --                 notconnec 1         auto    auto    10g       
Eth1/33       1/33_mud           connected 501       full    1000    10g       
Eth1/34       --                 disabled  1         auto    auto    10g       
Eth1/35       --                 notconnec 1         auto    auto    10g       
Eth1/36       --                 notconnec 1         auto    auto    10g       
Eth1/37       --                 notconnec 1         auto    auto    10g       
Eth1/38       --                 notconnec 1         auto    auto    10g       
Eth1/39       --                 notconnec 1         auto    auto    10g        
Eth1/40       --                 notconnec 1         auto    auto    10g       
Eth1/41       --                 notconnec 1         auto    auto    10g       
Eth1/42       --                 notconnec 1         auto    auto    10g       
Eth1/43       --                 notconnec 1         auto    auto    10g       
Eth1/44       --                 notconnec 1         auto    auto    10g       
Eth1/45       --                 notconnec 1         auto    auto    10g       
Eth1/46       --                 notconnec 1         auto    auto    10g       
Eth1/47       --                 notconnec 1         auto    auto    10g       
Eth1/48       --                 notconnec 1         auto    auto    10g       
Eth1/49       --                 notconnec 1         auto    auto    10g       
Eth1/50       --                 notconnec 1         auto    auto    10g       
Eth1/51       --                 notconnec 1         auto    auto    10g       
Eth1/52       --                 notconnec 1         auto    auto    10g       
Eth1/53       --                 notconnec 1         auto    auto    10g       
Eth1/54       --                 notconnec 1         auto    auto    10g       
Eth1/55       --                 notconnec 1         auto    auto    10g       
Eth1/56       --                 notconnec 1         auto    auto    10g       
Eth1/57       --                 notconnec 1         auto    auto    10g       
Eth1/58       --                 notconnec 1         auto    auto    10g       
Eth1/59       --                 notconnec 1         auto    auto    10g       
Eth1/60       --                 notconnec 1         auto    auto    10g       
Eth1/61       --                 notconnec 1         auto    auto    10g       
Eth1/62       --                 notconnec 1         auto    auto    10g       
Eth1/63       --                 notconnec 1         auto    auto    10g       
Eth1/64       --                 notconnec 1         auto    auto    10g       
Eth1/65       --                 notconnec 1         auto    auto    10g       
Eth1/66       --                 notconnec 1         auto    auto    10g       
Eth1/67       --                 notconnec 1         auto    auto    10g       
Eth1/68       --                 notconnec 1         auto    auto    10g       
Eth1/69       --                 notconnec 1         auto    auto    10g        
Eth1/70       --                 notconnec 1         auto    auto    10g       
Eth1/71       --                 notconnec 1         auto    auto    10g       
Eth1/72       --                 notconnec 1         auto    auto    10g       
Eth1/73       --                 notconnec 1         auto    auto    10g       
Eth1/74       --                 notconnec 1         auto    auto    10g       
Eth1/75       --                 notconnec 1         auto    auto    10g       
Eth1/76       --                 notconnec 1         auto    auto    10g       
Eth1/77       --                 notconnec 1         auto    auto    10g       
Eth1/78       --                 notconnec 1         auto    auto    10g       
Eth1/79       --                 notconnec 1         auto    auto    10g       
Eth1/80       --                 notconnec 1         auto    auto    10g       
Eth1/81       --                 notconnec 1         auto    auto    10g       
Eth1/82       --                 notconnec 1         auto    auto    10g       
Eth1/83       --                 notconnec 1         auto    auto    10g       
Eth1/84       --                 notconnec 1         auto    auto    10g       
Eth1/85       --                 notconnec 1         auto    auto    10g       
Eth1/86       --                 notconnec 1         auto    auto    10g       
Eth1/87       --                 notconnec 1         auto    auto    10g       
Eth1/88       --                 notconnec 1         auto    auto    10g       
Eth1/89       --                 notconnec 1         auto    auto    10g       
Eth1/90       --                 notconnec 1         auto    auto    10g       
Eth1/91       --                 notconnec 1         auto    auto    10g       
Eth1/92       --                 notconnec 1         auto    auto    10g       
Eth1/93       --                 notconnec 1         auto    auto    10g       
Eth1/94       --                 notconnec 1         auto    auto    10g       
Eth1/95       --                 notconnec 1         auto    auto    10g       
Eth1/96       --                 notconnec 1         auto    auto    10g       
Eth2/1        Ethernet2/1_hqlabd connected trunk     full    40G     QSFP-40G-SR-BD
Eth2/2        Ethernet2/2_hqlabd connected trunk     full    40G     QSFP-40G-SR-BD
Eth2/3        --                 xcvrAbsen 1         auto    auto    --        
Eth2/4        --                 xcvrAbsen 1         auto    auto    --        
Eth2/5        --                 xcvrAbsen 1         auto    auto    --        
Eth2/6        --                 xcvrAbsen 1         auto    auto    --        
Eth2/7        --                 xcvrAbsen 1         auto    auto    --        
Eth2/8        --                 xcvrAbsen 1         auto    auto    --        
Po3           --                 noOperMem 501       auto    auto    --        
Lo100         MP-BGP loopback    connected routed    auto    auto    --        
Lo101         VTEP loopback      connected routed    auto    auto    --        
Vlan1         --                 down      routed    auto    auto    --
Vlan50        spine1-leaf1-p2p   connected routed    auto    auto    --
Vlan52        spine2-leaf1-p2p   connected routed    auto    auto    --
Vlan100       evpn-dev-vni4vxlan connected routed    auto    auto    --
Vlan501       --                 connected routed    auto    auto    --
Vlan582       --                 connected routed    auto    auto    --
Vlan595       --                 down      routed    auto    auto    --
nve1          --                 connected --        auto    auto    --        
 
--------------------------------------------------------------------------------
Port          Name               Status    Vlan      Duplex  Speed   Type
--------------------------------------------------------------------------------
"""

cmd = "show interface status"

from genie.libs.parser.utils import get_parser
from genie.conf.base import Device, Testbed
from pyats.datastructures import AttrDict

device = Device("new_device", os="nxos")
device.custom.setdefault("abstraction", {})["order"] = ["os"]
device.cli = AttrDict({"execute": None})
get_parser(cmd, device)
parsed_output = device.parse(cmd, output=raw_cli_output)
print(parsed_output)
```

**Comment by tahigash** [comment]
We've identified the bug and fixed.
Please install beta package by below command. `genie.libs.parser` 20.8.1b3 has the fix.

```
pip install genie.libs.parser --upgrade --pre
```

Closing this issue, but if you still see the issue, please reopen.

**Comment by jamiecaesar** [comment]
Looks fixed to me.  Thanks for the quick response!
