### ISSUE TITLE
learn bgp fail on iox xr 5.2.4

### ISSUE THREAD

**Issue by zkzqzk** [CiscoTestAutomation/genieparser#296]
run device.learn('bgp') on iox xr 5.2.4, but it fails with below error.  could you please help?

Issue while parsing: <class 'genie.libs.parser.iosxr.show_bgp.ShowBgpInstanceAllAll'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/home/zuok/venvs/netdevops1/lib/python3.8/site-packages/genie/libs/ops/bgp/iosxr/bgp.py", line 546, in learn
    self.make()
  File "/home/zuok/venvs/netdevops1/lib/python3.8/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::40/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::60/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::80/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::b3/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::b4/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::b5/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::c0/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 7657:1511512001', 'prefix', '2407:7000:feed:1000::e0/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::40/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::60/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::80/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::b3/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::b5/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::c0/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981125', 'prefix', '2407:7000:feed:1000::e0/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::40/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::60/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::80/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::b4/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::b5/128', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::c0/123', 'index', 1, 'next_hop'], ['instance', 'default', 'vrf', 'default', 'address_family', 'vpnv6 unicast RD 17808:1210981126', 'prefix', '2407:7000:feed:1000::e0/123', 'index', 1, 'next_hop']]

**Comment by ThomasJRyan** [comment]
Hi there, this looks to be a parsing error. There's a good chance whatever the device output was didn't match what was expected. Are you able to provide the device output that would have been given right before this error occurred?

**Comment by zkzqzk** [comment]
Hi, how can I PM you the additional output?  or would you run learn BGP against a IOS-XR?  I think the issue can be replicated. I tried on a couple of different version, all give me the error.

**Comment by ThomasJRyan** [comment]
You can email me the output directly at `thomryan@cisco.com`

**Comment by bpastravanu** [comment]
When tried to learn BGP on IOS XR 6.5.3 I also got bellow:

Issue while parsing: <class 'genie.libs.parser.iosxr.show_bgp.ShowBgpInstances'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/usr/local/lib/python3.6/site-packages/genie/libs/ops/bgp/iosxr/bgp.py", line 546, in learn
    self.make()
  File "/usr/local/lib64/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['instance']]

===

I also tried parsing 'show bgp summary' with no luck:

Issue with the parser show bgp summary

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/bogdan.pastravanu/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 6654, in cli
    return super().cli(output=out, address_family=address_family)
  File "/home/bogdan.pastravanu/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 4673, in cli
    bgp_instance_summary_dict['instance'][instance]['vrf'][vrf]['address_family'][address_family]['generic_scan_interval'] = generic_scan_interval
KeyError: 'instance'

**Comment by zkzqzk** [comment]
Yes, this is the exact problem I am facing,  looks like something related to the parser as you said.   It would be great if it can be fixed in the coming updates.

Regards,

Ken
________________________________
发件人: bpastravanu <notifications@github.com>
发送时间: 2020年10月20日 14:11
收件人: CiscoTestAutomation/genieparser <genieparser@noreply.github.com>
抄送: zkzqzk <zkzqzk@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [CiscoTestAutomation/genieparser] learn bgp fail on iox xr 5.2.4 (#296)


When tried to learn BGP on IOS XR 6.5.3 I also got bellow:

Issue while parsing: <class 'genie.libs.parser.iosxr.show_bgp.ShowBgpInstances'>

Traceback (most recent call last):
File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
File "/usr/local/lib/python3.6/site-packages/genie/libs/ops/bgp/iosxr/bgp.py", line 546, in learn
self.make()
File "/usr/local/lib64/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
self.maker.make(*args, **kwargs)
File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['instance']]

===

I also tried parsing 'show bgp summary' with no luck:

Issue with the parser show bgp summary

Traceback (most recent call last):
File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
File "/home/bogdan.pastravanu/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 6654, in cli
return super().cli(output=out, address_family=address_family)
File "/home/bogdan.pastravanu/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 4673, in cli
bgp_instance_summary_dict['instance'][instance]['vrf'][vrf]['address_family'][address_family]['generic_scan_interval'] = generic_scan_interval
KeyError: 'instance'

―

**Comment by ThomasJRyan** [comment]
Hm... Alright, it's almost certainly due to the parser being developed for a newer/older version of IOSXR. I can get this fixed up for the next release for you!

**Comment by bpastravanu** [comment]
Sounds great, thanks Thomas!

**Comment by zkzqzk** [comment]
Thank you very much! Thomas.

Regards,

Ken
________________________________
发件人: bpastravanu <notifications@github.com>
发送时间: 2020年10月22日 15:04
收件人: CiscoTestAutomation/genieparser <genieparser@noreply.github.com>
抄送: zkzqzk <zkzqzk@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [CiscoTestAutomation/genieparser] learn bgp fail on iox xr 5.2.4 (#296)


Sounds great, thanks Thomas!

―

**Comment by ThomasJRyan** [comment]
I'm going to need the output for the commands
```
show bgp summary
show bgp instances
show bgp instance all all all
```
To fix these parsers. Would you mind emailing them to pyats-support-ext@cisco.com and including my name in them please? Thank you

**Comment by ThomasJRyan** [comment]
I've gotten an unreleased fix made for `show bgp instance all all all`. I still need the output from @bpastravanu's commands to fix those up though

**Comment by zkzqzk** [comment]
Thank you very much for the update.

Let me know if you need anything else from me for resolving the issue.

Thanks,

Ken

**Comment by bpastravanu** [comment]
> I've gotten an unreleased fix made for `show bgp instance all all all`. I still need the output from @bpastravanu's commands to fix up the rest though

Submitted Thomas, thank you.

**Comment by ThomasJRyan** [comment]
Alright. Thank you both for being so patient with this. I've released a beta package that will fix your issues up. You can install it like so:

`pip install --pre genie.libs.parser`

If there are any other issues feel free to open up another post!
