### ISSUE TITLE
NXOS vlan_dict referenced before assignment

### ISSUE THREAD

**Issue by rick-allen-206** [CiscoTestAutomation/genieparser#308]
`Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/sage/.local/lib/python3.6/site-packages/genie/libs/parser/nxos/show_interface.py", line 2910, in cli
    intf_dict = vlan_dict.\
UnboundLocalError: local variable 'vlan_dict' referenced before assignment`

**Comment by KamyarZiabari** [comment]
Hi @rick-allen-206 
Can you please provide a sample CLI output of what is causing this error?
Thanks!

**Comment by rick-allen-206** [comment]
This is the command being run: `pyats parse 'show interface brief' --testbed-file sample_testbed.yaml --devices hq-core-n9k-02`
This is the output:
```
Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/sage/Coding/nettest/env/lib/python3.6/site-packages/genie/libs/parser/nxos/show_interface.py", line 2910, in cli
    intf_dict = vlan_dict.\
UnboundLocalError: local variable 'vlan_dict' referenced before assignment
```

**Comment by rick-allen-206** [comment]
So far I have only tested this on NXOS

**Comment by KamyarZiabari** [comment]
Hi @rick-allen-206,

I meant if possible share the "show interface brief" output from that nxos device. Without having the device output I am not able to generate the error on my end. Is sharing that possible?

**Comment by rick-allen-206** [comment]
Yeah, sorry I didn't understand. Here is the output of that command.
[ShowInterfaceBrief.txt](https://github.com/CiscoTestAutomation/genieparser/files/5441506/ShowInterfaceBrief.txt)

**Comment by KamyarZiabari** [comment]
> Yeah, sorry I didn't understand. Here is the output of that command.
> [ShowInterfaceBrief.txt](https://github.com/CiscoTestAutomation/genieparser/files/5441506/ShowInterfaceBrief.txt)

Perfect thanks. Let me look into it and get back to you

**Comment by KamyarZiabari** [comment]
Hi @rick-allen-206  The fix is in place, and about to be merged. As soon as it is merged we release a beta for you and I will update you about how to have access to latest changes. 

Regards,
Kamyar

**Comment by KamyarZiabari** [comment]
Hi @rick-allen-206  A beta is released. You can have access to the latest changes by running this command. 

pip install --upgrade -pre genie.libs.parser which update your genieparser code and it will reflect the changes.

Let me know if anything 
Regards,
Kamyar

**Comment by rick-allen-206** [comment]
Thanks, I'll give it a go!
