### ISSUE TITLE
IOS-XR Error when Parsing "Show interfaces GigabitEthernet100/0/0/8"

### ISSUE THREAD

**Issue by vishnuo-lab** [CiscoTestAutomation/genieparser#332]
I'm getting error when parsing interfaces that being with 100/x/x/x (both for TE and GI interfaces). I am running the latest pyats 20.10 and Genie 20.10.

Error:

2020-11-05 10:44:56,083: %UNICON-INFO: +++ LABASR9912: executing command 'show interfaces GigabitEthernet100/0/0/8' +++
show interfaces GigabitEthernet100/0/0/8
Thu Nov  5 10:46:57.002 EST
GigabitEthernet100/0/0/8 is administratively down, line protocol is administratively down 
  Interface state transitions: 0
  Hardware is GigabitEthernet/IEEE 802.3 interface(s), address is 0000.0000.0000 (bia 0000.0000.0000)
  Description: reserved for Tracy Test
  Internet address is Unknown
  MTU 1514 bytes, BW 1000000 Kbit (Max: 1000000 Kbit)
     reliability 255/255, txload 0/255, rxload 0/255
  Encapsulation ARPA,
  Full-duplex, 1000Mb/s, link type is force-up
  output flow control is off, input flow control is off
  loopback not set,
  Last input never, output never
  Last clearing of "show interface" counters never
  5 minute input rate 0 bits/sec, 0 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     0 packets input, 0 bytes, 0 total input drops
     0 drops for unrecognized upper-level protocol
     Received 0 broadcast packets, 0 multicast packets
              0 runts, 0 giants, 0 throttles, 0 parity
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     0 packets output, 0 bytes, 0 total output drops
     Output 0 broadcast packets, 0 multicast packets
     0 output errors, 0 underruns, 0 applique, 0 resets
     0 output buffer failures, 0 output buffers swapped out
     0 carrier transitions

RP/0/RP0/CPU0:LABASR9912#
Traceback (most recent call last):
  File "DatacomAutomation.py", line 203, in <module>
    main()
  File "DatacomAutomation.py", line 160, in main
    internet_circuit_obj.circuit_list_of_dict, output_template_dict, genie_dict_of_obj, provider_edge_router)
  File "/home/vnathan/Automation/packages/Internet_Circuit.py", line 66, in __init__
    self.internet_main()
  File "/home/vnathan/Automation/packages/Internet_Circuit.py", line 566, in internet_main
    self.provider_edge_router)
  File "/home/vnathan/Automation/packages/Base_Circuit.py", line 38, in __init__
    self.check_interface()
  File "/home/vnathan/Automation/packages/Base_Circuit.py", line 392, in check_interface
    self.genie_dict_of_obj)
  File "/home/vnathan/Automation/packages/interface_check.py", line 196, in check_sub_interfaces
    check_main_interfaces(main_interface, provider_edge_router, description_compare, 'NO', genie_dict_of_obj)
  File "/home/vnathan/Automation/packages/interface_check.py", line 121, in check_main_interfaces
    provider_edge_router, pe_obj, interface)
  File "/home/vnathan/Automation/packages/interface_check.py", line 73, in interface_check
    provider_edge_router, genie_command)
  File "/home/vnathan/Automation/packages/Genie_Func.py", line 166, in genie_parse_func
    output = device_obj.parse(genie_command)
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['GigabitEthernet100/0/0/8', 'type

**Comment by ahersi2-cisco** [comment]
Hi vishnuo,

It appears the schema for this parser was requiring the key 'type' to be included, which your device output didn't include. Simply putting 'Optional' in front of the key 'type' will fix this issue. You could find it in the class 'ShowInterfacesSchema', in the file 'show_interface.py' under iosxr. I made the changes on my end and tested it, and it works fine. It will be included in the next release if you could make the changes on your end for now. I could also release a beta for you with the fix if you'd like. Let me know if this fixes your issue.

Thank you,
Abdurahman

**Comment by vishnuo-lab** [comment]
Hey Abdurahman,

I made the changes and it fixed the problem. Thanks for all your help.

**Comment by ahersi2-cisco** [comment]
Glad to help
