### ISSUE TITLE
Parser for show bgp summary failed

### ISSUE THREAD

**Issue by somebody78** [CiscoTestAutomation/genieparser#390]
Hello,

specifically I tested the command "show bgp instance <instance> vrf <vrf> <address_family> summary" and I got this error message:
>>> bgp_sum = device.parse("show bgp instance default vrf admmp ipv4 unicast summary")

2021-01-29 12:33:37,902: %UNICON-INFO: +++ router1 with alias 'mgmt': executing command 'show bgp instance default vrf admmp ipv4 unicast summary' +++
show bgp instance default vrf admmp ipv4 unicast summary
Fri Jan 29 12:33:38.069 MEZ
BGP VRF admmp, state: Active
BGP Route Distinguisher: 10.10.10.52:40001
VRF ID: 0x60000002
BGP router identifier 10.10.10.52, local AS number 65000
Non-stop routing is enabled
BGP table state: Active
Table ID: 0xe0000011   RD version: 3256863
BGP main routing table version 3258595
BGP NSR Initial initsync version 25 (Reached)
BGP NSR/ISSU Sync-Group versions 0/0

BGP is operating in STANDALONE mode.

Process       RcvTblVer   bRIB/RIB   LabelVer  ImportVer  SendTblVer  StandbyVer
Speaker         3258595    3258595    3258595    3258595     3258595           0

Neighbor        Spk    AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down  St/PfxRcd
10.161.240.18     0 64812 1259386 1259129  3258595    0    0    37w5d         44
10.161.240.19     0 64812 1259422 1259146  3258595    0    0    37w5d         44

RP/0/RSP0/CPU0:router1#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/users/ggcninetsdms/nornir-3.0.0/nornir-venv/lib64/python3.6/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 4647, in cli
    bgp_instance_summary_dict['instance'][instance]['vrf'][vrf]['address_family'][address_family]['route_distinguisher'] = route_distinguisher
KeyError: 'instance'
>>> 

It appears as the instance "default" might not be handled correctly.

Dirk

**Comment by badalsoyantar** [comment]
Hi @somebody78 Issue if fixed. Will ping you here once released.

**Comment by tahigash** [comment]
v21.2 was already released with the fix. closing.
