### ISSUE TITLE
IOSXR-show bfd session- Exception: Parser ShowBfdSession schema checking failed

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#411]
Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 244, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaTypeError: interface.Bundle-Ether1.dest_ip_address.10.10.10.10.echo_total_msec: Expected type '<class 'int'>' but got type 'n/a'(<class 'str'>)

  File "src/genie/conf/base/device.py", line 543, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 306, in genie.metaparser._metaparser.MetaParser.parse
Exception: Parser ShowBfdSession schema checking failed

**Comment by LukasMcClelland** [comment]
Hi Amrit, thank you for bringing this to our attention. I'll be working to fix this

**Comment by LukasMcClelland** [comment]
Could you please supply the device output that caused this error to happen?

**Comment by amrit-ma-siu** [comment]
This should be the one causing it as the values are n/a. And schema has it as <class 'int'>.

`#BE300               172.16.253.53   n/a              n/a              UP
        p3 = re.compile(
            r'^(?P<intf>\S+) +(?P<dest>\d+\.\d+\.\d+\.\d+) +(?P<echo_total_msec>\w+\/\w+) +(?P<async_total_msec>\w+\/\w+) +(?P<state>\S+) ?(?P<damp>\S+)?')`

**Comment by LukasMcClelland** [comment]
Hello again Amrit, a pull request for this bug has been merged and the fix will be included in the next release. Thanks again

**Comment by LukasMcClelland** [comment]
Hi Amrit, just letting you know that this fix has been released
