### ISSUE TITLE
lldp details parser needs to handle spaces in chassis_id and system_name

### ISSUE THREAD

**Issue by saparikh** [CiscoTestAutomation/genieparser#413]
The following output of `show lldp neighbors detail` results in a parser error:

Parser error:
```
Traceback (most recent call last):
  File "<ipython-input-53-fe4626fc7696>", line 60, in _parse
    parsed_output = device.parse(cmd, output=raw_cli_output)
  File "src/genie/conf/base/device.py", line 543, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 576, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['interfaces', 'Ethernet1/1', 'port_id', 'X3', 'neighbors']
```

output of `show lldp neighbors detail`:
```
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID            Local Intf      Hold-time  Capability  Port ID

Chassis id: f07f.06ab.8d40
Port id: Gi1/11
Local Port id: mgmt0
Port Description: foo
System Name: foo
System Description: Cisco IOS Software, Catalyst 4500 L3 Switch  Software (cat4500e-ENTSERVICESK9-M), Version 15.2(4)E2, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2016 by Cisco Systems, Inc.
Compiled Mon 27-Jun-16 10:02 by
Time remaining: 110 seconds
System Capabilities: B, R
Enabled Capabilities: B, R
Management Address: 10.255.1.111
Vlan ID: 402


Chassis id: ENC:abdqasad SERIAL NO:USE34059SDF
Port id: X3
Local Port id: Eth1/1
Port Description: 10000/full SFP-SR
System Name: LOC SERIAL NO:8CSEF8SDFMD BAY:2
System Description: HP VC Flex-10/10D Module 4.45 2015-07-21T00:14:47Z
Time remaining: 101 seconds
System Capabilities: not advertised
Enabled Capabilities: not advertised
Management Address: 10.255.66.8
Vlan ID: not advertised
```

Patching the regex for `Chassis id` and `System Name` to match anything till the end of the line fixes this issue.

Given that each field is on a newline, not sure why the parser is not setup to be more greedy.

**Comment by saparikh** [comment]
I was able to use this patch locally to address the issue.

```
diff --git a/src/genie/libs/parser/iosxe/show_lldp.py b/src/genie/libs/parser/iosxe/show_lldp.py
index 43b57ff9d..62edd50e7 100755
--- a/src/genie/libs/parser/iosxe/show_lldp.py
+++ b/src/genie/libs/parser/iosxe/show_lldp.py
@@ -179,7 +179,8 @@ class ShowLldpEntry(ShowLldpEntrySchema):
 
         # Chassis id:  843d.c6ff.f1b8
         # Chassis id: r2-rf2222-qwe
-        p2 = re.compile(r'^Chassis\s+id:\s+(?P<chassis_id>[\w\.\:\-]+)$')
+        #p2 = re.compile(r'^Chassis\s+id:\s+(?P<chassis_id>[\w\.\:\-]+)$')
+        p2 = re.compile(r'^Chassis\s+id:\s+(?P<chassis_id>.+?)\s*$')
 
         # Port Description: GigabitEthernet1/0/4
         p3 = re.compile(r'^Port\s+Description:\s+(?P<desc>[\w\/\.\-\s]+)$')
diff --git a/src/genie/libs/parser/nxos/show_lldp.py b/src/genie/libs/parser/nxos/show_lldp.py
index 33a21104f..24ad3c05b 100644
--- a/src/genie/libs/parser/nxos/show_lldp.py
+++ b/src/genie/libs/parser/nxos/show_lldp.py
@@ -248,7 +248,8 @@ class ShowLldpNeighborsDetail(ShowLldpNeighborsDetailSchema):
         tmp_port_id = ''
         # Chassis id: 000d.bdff.4f04
         # Chassis id: 39373638-3935-5A43-4A37-35303036574C
-        p1 = re.compile(r'^Chassis +id: +(?P<chassis_id>[\S]+)$')
+        #p1 = re.compile(r'^Chassis +id: +(?P<chassis_id>[\S]+)$')
+        p1 = re.compile(r'^Chassis +id: +(?P<chassis_id>.+?)\s*$')
         # Port id: Gi0/0/0/1
         # Port id: PCI-E Slot 1, Port 2
         p2 = re.compile(r'^Port +id: +(?P<port_id>[\S ]+)$')
@@ -257,9 +258,10 @@ class ShowLldpNeighborsDetail(ShowLldpNeighborsDetailSchema):
         # Port Description: null
         p4 = re.compile(r'^Port +Description: +(?P<port_description>(?!null).+)$')
         # System Name: R2_xrv9000
-        p5 = re.compile(r'^System +Name: +(?P<system_name>\S+)$')
+        #p5 = re.compile(r'^System +Name: +(?P<system_name>\S+)$')
+        p5 = re.compile(r'^System +Name: +(?P<system_name>.+?)\s*$')
         # System Description:  6.2.2, IOS-XRv 9000
-        p6 = re.compile(r'^System +Description: +(?P<system_description>.+)$')
+        p6 = re.compile(r'^System +Description: +(?P<system_description>.+?)\s*$')
         # Copyright (c) 1986-2017 by Cisco Systems, Inc.
         p6_1 = re.compile(r'^(?P<copyright>Copyright +\([c|C]\) +.+)$')
         # Compiled Sat 22-Jul-17 05:51 by
```

**Comment by kazemy** [comment]
Hi Samir and thank you for reaching out.
A pull request for this bug has been pushed and the fix is being reviewed. 
I will let you know when the fix is merged.
Thank you!

**Comment by saparikh** [comment]
👍🏽

**Comment by kazemy** [comment]
Hi Samir,
the PR completed review and is merged.
the fix will be available on our next general release.
I will close this issue.
Thank you!

**Comment by saparikh** [comment]
cool, thanks.
