### ISSUE TITLE
Pyats.utils.exception : Missing keys when a test playbook ran against sbx

### ISSUE THREAD

**Issue by bronitskiy** [CiscoTestAutomation/genieparser#414]
Having issues running a test playbook (with genie learn arp module) and the following exception returned:
```
 pyats.utils.exceptions.SchemaMissingKeyError: Missing keys:
      "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
      "type"  parent: [devices.sbx-nxos-mgmt.cisco.com]
```
As it was advised by clay584/genie_collection here: https://github.com/clay584/genie_collection/issues/6#issuecomment-804088289 this seems to be an issues with the parser.

The full output can be found below:
```
(.venv) [root@292c4c38a3f8 genie_collection-master]# pwd
/genie_collection-master
(.venv) [root@292c4c38a3f8 genie_collection-master]# tree
.
|-- LICENSE
|-- NOTICE
|-- Pipfile
|-- Pipfile.lock
|-- README.md
|-- ansible.cfg
|-- clay584
|   `-- genie
|       |-- README.md
|       |-- clay584-genie-0.1.7.tar.gz
|       |-- colored_diff.png
|       |-- galaxy.yml
|       |-- learn_genie_params.png
|       `-- plugins
|           |-- filter
|           |   `-- parse_genie.py
|           `-- modules
|               |-- args.json
|               `-- learn_genie.py
|-- genie_filter_testing.yml
|-- inventory
|-- test.yml
|-- test_arp.yaml
-- yamllint_config.yml
5 directories, 19 files
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# cat test_arp.yaml
---
- hosts: all
  gather_facts: false
  connection: local
  collections:
   - clay584.genie
  tasks:
    - name: Learn Genie - ARP
      learn_genie:
        host: "{{ ansible_host }}"
        port: 8181
        protocol: ssh
        username: admin
        password: Admin_1234!
        os: nxos
        feature: arp
      register: genie_arp1
    - name: Debug Genie
      debug:
        msg: "{{ genie_arp1 }}"
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# ansible --version
ansible 2.10.6
  config file = /genie_collection-master/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/genie_collection-master/clay584/genie/plugins/modules']
  ansible python module location = /.venv/lib64/python3.6/site-packages/ansible
  executable location = /.venv/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# cat inventory
all:
  hosts:
    sbx-nxos-mgmt.cisco.com:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
```

```
(.venv) [root@292c4c38a3f8 genie_collection-master]# ansible-playbook test_arp.yaml -i inventory -v
Using /genie_collection-master/ansible.cfg as config file

PLAY [all] ************************************************************************************************************************************************************

TASK [Learn Genie - ARP] **********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
fatal: [sbx-nxos-mgmt.cisco.com]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1615507860.465231-957-197841320397725/AnsiballZ_learn_genie.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1615507860.465231-957-197841320397725/AnsiballZ_learn_genie.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1615507860.465231-957-197841320397725/AnsiballZ_learn_genie.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.clay584.genie.plugins.modules.learn_genie', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_learn_genie_payload_s18eg0q9/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 367, in <module>
      File "/tmp/ansible_learn_genie_payload_s18eg0q9/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 363, in main
      File "/tmp/ansible_learn_genie_payload_s18eg0q9/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 296, in run_module
      File "src/genie/testbed.py", line 4, in genie.testbed.load
      File "src/genie/conf/main.py", line 81, in genie.conf.main.Genie.init
      File "/.venv/lib64/python3.6/site-packages/pyats/topology/loader/__init__.py", line 41, in load
        return TestbedFileLoader(**init_kwargs).load(loadable, **kwargs)
      File "src/pyats/utils/yaml/loader.py", line 134, in pyats.utils.yaml.loader.Loader.load
      File "src/pyats/utils/schemaengine.py", line 403, in pyats.utils.schemaengine.Schema.validate
    pyats.utils.exceptions.SchemaMissingKeyError: Missing keys:
      "type"  parent: [devices.sbx-nxos-mgmt.cisco.com]
      "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ************************************************************************************************************************************************************
sbx-nxos-mgmt.cisco.com    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by danielgraziano** [comment]
@bronitskiy this looks to be a schema issue with your testbed yaml file. The device `sbx-nxos-mgmt.cisco.com` is missing two mandatory keys, `type` and `connections`. 

Without seeing your testbed file it would be hard for me to point out the exact location but it should look something like below:
```yaml
devices:
  'sbx-nxos-mgmt.cisco.com':
    type: <any string to describe it>
    connections:
      ...
```

For the full schema you can look here: https://pubhub.devnetcloud.com/media/pyats/docs/topology/schema.html
If you search for `type:   # device type generic string` and `block describing the 'ways', 'methods' and 'paths' of` you will see the two keys that are missing.

**Comment by bronitskiy** [comment]
Thanks for getting back to me @danielgraziano.
Since I am using ansible collection (https://github.com/clay584/genie_collection) and a playbook that is calling "learn_genie" module,  I am not too sure if I still need to have a testbed file created manually? 
I was hopping that a standard "ansible inventory yaml file" would be sufficient. 
Eg. this is what it looks like at the moment on my ansible host:
```
(.venv) [root@292c4c38a3f8 genie_collection-master]# cat inventory
all:
  hosts:
    sbx-nxos-mgmt.cisco.com:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
```
Can I simply add those missing "type" and "connection" parameters to ansible inventory file somehow?
Or do I still need a pyats testbed file created as well?!

**Comment by clay584** [comment]
Looks like there was a breaking change in going from pyATS 21.1 to 21.2.

Version 21.1
-------------
```
pyats version check
You are currently running pyATS version: 21.1
Python: 3.7.9 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.1.2 
  genie.libs.clean             21.1   
  genie.libs.conf              21.1   
  genie.libs.filetransferutils 21.1   
  genie.libs.health            21.1   
  genie.libs.ops               21.1   
  genie.libs.parser            21.1   
  genie.libs.sdk               21.1.2 
  pyats                        21.1   
  pyats.aereport               21.1   
  pyats.aetest                 21.1   
  pyats.async                  21.1   
  pyats.connections            21.1   
  pyats.datastructures         21.1   
  pyats.easypy                 21.1   
  pyats.kleenex                21.1   
  pyats.log                    21.1   
  pyats.reporter               21.1   
  pyats.results                21.1   
  pyats.tcl                    21.1   
  pyats.topology               21.1   
  pyats.utils                  21.1.1 
  unicon                       21.1   
  unicon.plugins               21.1   
```
@bronitskiy code works as expected.

```
TASK [Debug Genie] *********************************************************************************************************************************************
ok: [sbx-nxos-mgmt.cisco.com] => {
    "msg": {
        "changed": false,
        "failed": false,
        "genie": {
            "arp": {
                "interfaces": {
                    "Ethernet1/5": {
                        "arp_dynamic_learning": {
                            "local_proxy_enable": false,
                            "proxy_enable": false
                        }
                    },
                    "Vlan100": {
                        "arp_dynamic_learning": {
                            "local_proxy_enable": false,
                            "proxy_enable": false
                        }
                    },
                    "Vlan101": {
                        "arp_dynamic_learning": {
                            "local_proxy_enable": false,
                            "proxy_enable": false
                        }
                    },
                    "Vlan102": {
                        "arp_dynamic_learning": {
                            "local_proxy_enable": false,
                            "proxy_enable": false
                        }
                    },
                    "Vlan103": {
                        "arp_dynamic_learning": {
                            "local_proxy_enable": false,
                            "proxy_enable": false
                        }
                    },
                    "Vlan104": {
                        "arp_dynamic_learning": {
                            "local_proxy_enable": false,
                            "proxy_enable": false
                        }
                    },
```

With Version 21.2 it breaks.

```
pyats version check 
You are currently running pyATS version: 21.2
Python: 3.7.9 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.2.3 
  genie.libs.clean             21.2   
  genie.libs.conf              21.2   
  genie.libs.filetransferutils 21.2   
  genie.libs.health            21.2   
  genie.libs.ops               21.2   
  genie.libs.parser            21.2.7 
  genie.libs.robot             21.2   
  genie.libs.sdk               21.2.1 
  genie.telemetry              21.2   
  genie.trafficgen             21.2   
  pyats                        21.2   
  pyats.aereport               21.2   
  pyats.aetest                 21.2   
  pyats.async                  21.2   
  pyats.connections            21.2.1 
  pyats.contrib                21.2   
  pyats.datastructures         21.2   
  pyats.easypy                 21.2   
  pyats.kleenex                21.2   
  pyats.log                    21.2   
  pyats.reporter               21.2   
  pyats.results                21.2   
  pyats.robot                  21.2   
  pyats.tcl                    21.2   
  pyats.topology               21.2   
  pyats.utils                  21.2   
  unicon                       21.2   
  unicon.plugins               21.2   

```


```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
fatal: [sbx-nxos-mgmt.cisco.com]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/ccurtis/.ansible/tmp/ansible-tmp-1617204683.4430048-17526-63656347877535/AnsiballZ_learn_genie.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ccurtis/.ansible/tmp/ansible-tmp-1617204683.4430048-17526-63656347877535/AnsiballZ_learn_genie.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ccurtis/.ansible/tmp/ansible-tmp-1617204683.4430048-17526-63656347877535/AnsiballZ_learn_genie.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.clay584.genie.plugins.modules.learn_genie', init_globals=None, run_name='__main__', alter_sys=True)
  File "/home/ccurtis/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/ccurtis/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/ccurtis/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_learn_genie_payload_o4y5zzm3/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 367, in <module>
  File "/tmp/ansible_learn_genie_payload_o4y5zzm3/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 363, in main
  File "/tmp/ansible_learn_genie_payload_o4y5zzm3/ansible_learn_genie_payload.zip/ansible_collections/clay584/genie/plugins/modules/learn_genie.py", line 296, in run_module
  File "src/genie/testbed.py", line 4, in genie.testbed.load
  File "src/genie/conf/main.py", line 81, in genie.conf.main.Genie.init
  File "/home/ccurtis/.virtualenvs/ansible-help/lib/python3.7/site-packages/pyats/topology/loader/__init__.py", line 41, in load
    return TestbedFileLoader(**init_kwargs).load(loadable, **kwargs)
  File "src/pyats/utils/yaml/loader.py", line 134, in pyats.utils.yaml.loader.Loader.load
  File "src/pyats/utils/schemaengine.py", line 403, in pyats.utils.schemaengine.Schema.validate
pyats.utils.exceptions.SchemaMissingKeyError: Missing keys:
  "type"  parent: [devices.sbx-nxos-mgmt.cisco.com]
  "connections"  parent: [devices.sbx-nxos-mgmt.cisco.com]
```

**Comment by danielgraziano** [comment]
@clay584 Prior to `21.2` we never did any schema validation if you create the testbed by passing a dictionary to `genie.testbed.load`. By accident this was overlooked and was fixed in `21.2` to prevent invalid testbeds from being created. Testbeds must follow the schema defined here: https://pubhub.devnetcloud.com/media/pyats/docs/topology/schema.html#production-yaml-schema

Here is a snippet from the above schema for the missing keys:
```
# devices block
# -------------
#   all testbed devices are described here
devices:

    <name>: # device name (hostname) goes here. Each device requires its
            # own description section within devices block

        type:   # device type generic string
                # use this to describe the type of device
                #   Eg: ASR9k
                # (required)

        connections:
            # block describing the 'ways', 'methods' and 'paths' of
            # connecting to this device. eg, telnet, ssh, netconf, etc
            # (required)

            defaults:
                # block used to specify and/or alter the default
                # connection manager behavior
                # (optional)

                class:  # the default connection implementation class to be
                        # used by connection manager when arguments such as
                        # 'cls' in connect() and 'factory' in start_pool()
                        # is not provided.
                        # (optional)

                alias:  # the default alias name if 'alias' is not provided
                        # to apis such as connect(), start_pool(), etc.
                        # (optional)

                via:    # the default path to use if 'via' is not provided
                        # to apis such as connect(), start_pool(), etc.
                        # (default: None - let the connection class decide)
                        # (optional)

                connections: # a list of subconnections for a multi-console
                             # device.
                             # Supported by unicon connector implementation.
                             # (optional)

                connections_arguments: # arguments to apply when creating a
                             # multi-console device connection.
                             # Supported by unicon connector implementation.
                             # (optional)
                             <key>: <value>


            <name>:
                # connection information on methods/ways to talk to this
                # testbed device.
                # (optional)

                class:  # connection class to use. use this field to
                        # provide an alternative connection class to use
                        # to connect to this connection
                        # (default to the above default/class)
                        # (optional)

                protocol:   # connection protocol
                            # (optional)

                host:   # device hostname
                        # (optional)

                ip:     # device connection ip address
                        # if a hostname is provided in the ip block,
                        # it be dns lookup-up and converted to IP address
                        # during testbed yaml loading.
                        # (optional)

                port:   # port to connect to
                        # (optional)

                credentials:
                    # credential details specific to this connection
                    # (optional)

                    # All credentials in the device and testbed credentials
                    # blocks are also available if not specified here.

                    <key>:        # Name of this credential.
                        username: # (optional)
                        password: # (optional)

                        # Any other credential details
                        <key>: <value>

                # all other key/values under a connection information block
                # that gets passed to the connection class constructor
                <key>: <value>

**Comment by danielgraziano** [comment]
@clay584 Sorry I deleted my previous comment as this seems to be an issue on our side. Looking into it further.

**Comment by bronitskiy** [comment]
@danielgraziano @clay584 thanks for looking into this guys, really appreciate it! :)

**Comment by danielgraziano** [comment]
@bronitskiy just an update, I should be releasing a new package today with the fix.

**Comment by danielgraziano** [comment]
@bronitskiy can you please upgrade the genie package to `21.3.1` you can do this by running `pip install --upgrade pyats[full]`

**Comment by bronitskiy** [comment]
@danielgraziano Yes, seems to be working now with the new release of pyats! Thank you and @clay584 for getting this resolved that quick and have a wonderful weekend!

**Comment by danielgraziano** [comment]
Thanks for verifying, closing this issue.
