### ISSUE TITLE
IOSXE - 'show wireless mobility summary' - Parser output is empty

### ISSUE THREAD

**Issue by oianson** [CiscoTestAutomation/genieparser#417]
Hi

On IOSXE with the 'show wireless mobility summary' parser, I am getting the following error:

```
SchemaEmptyParserError: Parser Output is empty
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 120, in metaparser_on_device
    return self.metaparser_on_device_alias_context(device=device,
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 161, in metaparser_on_device_alias_context
    return con.parse(parser)
  File "src/genie/conf/base/device.py", line 522, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 290, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 222, in genie.metaparser.util.schemaengine.Schema.validate
```

The output for reference.. 
```
Mobility Summary

Wireless Management VLAN: 143
Wireless Management IP Address: 10.20.30.40
Wireless Management IPv6 Address: 
Mobility Control Message DSCP Value: 48
Mobility Keepalive Interval/Count: 10/3
Mobility Group Name: default
Mobility Multicast Ipv4 address: 0.0.0.0
Mobility Multicast Ipv6 address: ::
Mobility MAC Address: 687d.b4fd.bbeb
Mobility Domain Identifier: 0x34ac

Controllers configured in the Mobility Domain:

 IP                                        Public Ip                                  MAC Address         Group Name                       Multicast IPv4    Multicast IPv6                              Status                       PMTU 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1.2.3.4                                N/A                                        AAAA.BBBB.CCCC      default                          0.0.0.0           ::                                          N/A                          N/A
```

**Comment by LukasMcClelland** [comment]
Thank you for bringing this to our attention. I'm working to fix this issue

**Comment by LukasMcClelland** [comment]
Hi @oianson, just letting you know that a pull request that contains a fix for this issue has been merged and will be included in the next release

**Comment by oianson** [comment]
Thanks @LukasMcClelland  :) !
