### ISSUE TITLE
IOS - show spanning tree parser fails when backbone_fast or uplink_fast do not appear in output

### ISSUE THREAD

**Issue by TestingBytes** [CiscoTestAutomation/genieparser#420]
Example failure from switch running 12.2(50)SE3:

```
show spanning-tree summary
Switch is in rapid-pvst mode
Root bridge for: VLAN0001, VLAN0002, VLAN0003, VLAN0004, VLAN0005, VLAN0006
  VLAN0007, VLAN0008, VLAN0009
Extended system ID           is enabled
Portfast Default             is enabled
PortFast BPDU Guard Default  is enabled
Portfast BPDU Filter Default is disabled
Loopguard Default            is disabled
EtherChannel misconfig guard is enabled
Configured Pathcost method used is short

Name                   Blocking Listening Learning Forwarding STP Active
---------------------- -------- --------- -------- ---------- ----------
VLAN0001                     0         0        0          5          5
VLAN0002                     0         0        0          5          5
VLAN0003                     0         0        0          5          5
VLAN0004                     0         0        0          6          6
VLAN0005                     0         0        0          5          5
VLAN0006                     0         0        0          5          5
VLAN0007                     0         0        0          5          5
VLAN0008                     0         0        0          5          5
VLAN0009                     0         0        0          5          5
---------------------- -------- --------- -------- ---------- ----------
9 vlans                      0         0        0         46         46
lab#
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 522, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['backbone_fast'], ['uplink_fast']]
```

**Comment by TestingBytes** [comment]
This parser uses the IOSXE parser `genieparser/src/genie/libs/parser/iosxe/show_spanning_tree.py`

Those two keys are current required (see below). I believe this parser would work if those keys were made optional.

```
class ShowSpanningTreeSummarySchema(MetaParser):
    """Schema for show spanning-tree summary"""
    schema = {
        Optional('etherchannel_misconfig_guard'): bool,
        Optional('extended_system_id'): bool,
        Optional('portfast_default'): bool,
        'bpdu_guard': bool,
        Optional('bpdu_filter'): bool,
        Optional('bridge_assurance'): bool,
        Optional('loop_guard'): bool,
        'uplink_fast': bool,     <-----------
        'backbone_fast': bool,  <----------
        Optional('root_bridge_for'): str,
```

**Comment by KamyarZiabari** [comment]
@LukasMcClelland  this PR is created for this issue. Can you please work on reviewing this. Thank you
https://github.com/CiscoTestAutomation/genieparser/pull/421

**Comment by LukasMcClelland** [comment]
Reviewed and left comments
