### ISSUE TITLE
IOSXR - show bgp instance all all all summary - Not parsing for IPv6 with dotted ASN

### ISSUE THREAD

**Issue by amrit-ma-siu** [CiscoTestAutomation/genieparser#428]
v21.3

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 522, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/test/venv/lib64/python3.6/site-packages/genie/libs/parser/iosxr/show_bgp.py", line 4795, in cli
    bgp_instance_summary_dict['instance'][instance]['vrf'][vrf]['neighbor'][neighbor]['remote_as'] = int(m.groupdict()['remote_as'])
**ValueError: invalid literal for int() with base 10: '65101.60000'**

https://github.com/CiscoTestAutomation/genieparser/blob/27f496ef70b5a003747fb8bdac6e7356ce508423/src/genie/libs/parser/iosxr/show_bgp.py#L4795

above line should be similar to below that is used for IPv4 [ Line 4826 ]

`try:`
`    bgp_instance_summary_dict['instance'][instance]['vrf'][vrf]['neighbor'][neighbor]['remote_as'] = int(m.groupdict()['remote_as'])`
`except:`
`    bgp_instance_summary_dict['instance'][instance]['vrf'][vrf]['neighbor'][neighbor]['remote_as'] = m.groupdict()['remote_as']`

**Comment by LukasMcClelland** [comment]
Hi @amrit-ma-siu, thank you for bringing this to our attention. I'll start working on a fix for this soon

**Comment by LukasMcClelland** [comment]
Hello @amrit-ma-siu, I believe your suggestion of how to change the code will work well. Would you be willing to provide the full output from the device when the command is issued? It would be helpful to use as a test. Thank you

**Comment by LukasMcClelland** [comment]
A pull request containing a fix for this issue has been merged and the fix for this issue will be included in the next release.

Thank you again
