### ISSUE TITLE
Show inventory IOSXE, "SchemaEmptyParserError: Parser Output is empty"

### ISSUE THREAD

**Issue by wilbeacham85** [CiscoTestAutomation/genieparser#431]
Hi I get a "SchemaEmptyParserError: Parser Output is empty" when running the Show inventory command on IOSXE device

INFO
```
2021-04-19 13:25:52,548: %UNICON-INFO: +++ C3650-CX-12PC with alias 'Corp_Telnet': executing command 'show inventory' +++
show inventory
NAME: "1", DESCR: "WS-C3560CX-12PC-S"
PID: WS-C3560CX-12PC-S , VID: V03  , SN: FOC2419L9KY
```
I get the following traceback
DEBUG
```
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 120, in metaparser_on_device
    return self.metaparser_on_device_alias_context(device=device,
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 161, in metaparser_on_device_alias_context
    return con.parse(parser)
  File "src/genie/conf/base/device.py", line 522, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 290, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 222, in genie.metaparser.util.schemaengine.Schema.validate
```

**Comment by LukasMcClelland** [comment]
Hi @wilbeacham85, thank you for bringing this to our attention.

A fix for this have been found and is currently under code review

**Comment by LukasMcClelland** [comment]
Fix has been merged and will be included in next release. Thanks again!
