### ISSUE TITLE
NXOS: Show interface status - SchemaMissingKeyError

### ISSUE THREAD

**Issue by oianson** [CiscoTestAutomation/genieparser#444]
The 'show interface status' parser for NXOS isn't working with the following output.

```
SchemaMissingKeyError: Missing keys: [['interfaces', 'Loopback0', 'port_speed'], ['interfaces', 'Loopback1', 'port_speed'], ['interfaces', 'Loopback1023', 'port_speed'], ['interfaces', 'Interface', 'status'], ['interfaces', 'Tunnel7', 'status'], ['interfaces', 'Tunnel8', 'status'], ['interfaces', 'Tunnel36', 'status'], ['interfaces', 'Tunnel37', 'status'], ['interfaces', 'Tunnel38', 'status'], ['interfaces', 'Tunnel39', 'status'], ['interfaces', 'Tunnel40', 'status'], ['interfaces', 'Tunnel41', 'status'], ['interfaces', 'Tunnel42', 'status'], ['interfaces', 'Tunnel43', 'status'], ['interfaces', 'Tunnel44', 'status'], ['interfaces', 'Tunnel45', 'status'], ['interfaces', 'Tunnel46', 'status'], ['interfaces', 'Tunnel47', 'status']]

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 120, in metaparser_on_device
    return self.metaparser_on_device_alias_context(device=device,
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 161, in metaparser_on_device_alias_context
    return con.parse(parser)
  File "src/genie/conf/base/device.py", line 522, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 549, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
```

```
----------------------------------------------------------------------------------------------
 Port           Name                Status     Vlan       Duplex   Speed    Type              
----------------------------------------------------------------------------------------------
 mgmt0          --                  connected  routed     full     1G       --               
 Eth1/1         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/2         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/3         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/4         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/5         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/6         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/7         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/8         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/9         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/10        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/11        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/12        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/13        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/14        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/15        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/16        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/17        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/18        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/19        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/20        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/21        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/22        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/23        --                  out-of-ser trunk      full     40G      QSFP-40G-SR-BD   
 Eth1/24        --                  notconnect trunk      full     inherit  QSFP-40G-SR-BD   
 Eth1/25        --                  sfpabsent  routed     full     inherit  --               
 Eth1/25.1      --                  parentdown routed     full     inherit  --               
 Eth1/26        --                  sfpabsent  routed     full     inherit  --               
 Eth1/26.2      --                  parentdown routed     full     inherit  --               
 Eth1/27        --                  sfpabsent  routed     full     inherit  --               
 Eth1/27.3      --                  parentdown routed     full     inherit  --               
 Eth1/28        --                  sfpabsent  routed     full     inherit  --               
 Eth1/28.4      --                  parentdown routed     full     inherit  --               
 Eth1/29        --                  sfpabsent  routed     full     inherit  --               
 Eth1/29.5      --                  parentdown routed     full     inherit  --               
 Eth1/30        --                  sfpabsent  routed     full     inherit  --               
 Eth1/30.6      --                  parentdown routed     full     inherit  --               
 Eth1/31        --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Eth1/31.21     --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Eth1/32        --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Eth1/32.22     --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Lo0            --                  connected  routed     auto     --       --               
 Lo1            --                  connected  routed     auto     --       --               
 Lo1023         --                  connected  routed     auto     --       --               

----------------------------------------------------------------
 Interface     Name                Status    Reason             
----------------------------------------------------------------
 Tunnel7       --                  up        no-reason         
 Tunnel8       --                  up        no-reason         
 Tunnel36      --                  up        no-reason         
 Tunnel37      --                  up        no-reason         
 Tunnel38      --                  up        no-reason         
 Tunnel39      --                  up        no-reason         
 Tunnel40      --                  up        no-reason         
 Tunnel41      --                  up        no-reason         
 Tunnel42      --                  up        no-reason         
 Tunnel43      --                  up        no-reason         
 Tunnel44      --                  up        no-reason         
 Tunnel45      --                  up        no-reason         
 Tunnel46      --                  up        no-reason         
 Tunnel47      --                  up        no-reason         
LEA-3102-I-y1801021# 
LEA-3102-I-y1801021# 
LEA-3102-I-y1801021# 
LEA-3102-I-y1801021# 
LEA-3102-I-y1801021# show interface status
----------------------------------------------------------------------------------------------
 Port           Name                Status     Vlan       Duplex   Speed    Type              
----------------------------------------------------------------------------------------------
 mgmt0          --                  connected  routed     full     1G       --               
 Eth1/1         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/2         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/3         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/4         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/5         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/6         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/7         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/8         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/9         --                  sfpabsent  trunk      full     inherit  --               
 Eth1/10        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/11        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/12        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/13        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/14        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/15        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/16        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/17        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/18        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/19        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/20        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/21        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/22        --                  sfpabsent  trunk      full     inherit  --               
 Eth1/23        --                  out-of-ser trunk      full     40G      QSFP-40G-SR-BD   
 Eth1/24        --                  notconnect trunk      full     inherit  QSFP-40G-SR-BD   
 Eth1/25        --                  sfpabsent  routed     full     inherit  --               
 Eth1/25.1      --                  parentdown routed     full     inherit  --               
 Eth1/26        --                  sfpabsent  routed     full     inherit  --               
 Eth1/26.2      --                  parentdown routed     full     inherit  --               
 Eth1/27        --                  sfpabsent  routed     full     inherit  --               
 Eth1/27.3      --                  parentdown routed     full     inherit  --               
 Eth1/28        --                  sfpabsent  routed     full     inherit  --               
 Eth1/28.4      --                  parentdown routed     full     inherit  --               
 Eth1/29        --                  sfpabsent  routed     full     inherit  --               
 Eth1/29.5      --                  parentdown routed     full     inherit  --               
 Eth1/30        --                  sfpabsent  routed     full     inherit  --               
 Eth1/30.6      --                  parentdown routed     full     inherit  --               
 Eth1/31        --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Eth1/31.21     --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Eth1/32        --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Eth1/32.22     --                  connected  routed     full     100G     QSFP-40/100-SRBD 
 Lo0            --                  connected  routed     auto     --       --               
 Lo1            --                  connected  routed     auto     --       --               
 Lo1023         --                  connected  routed     auto     --       --               

----------------------------------------------------------------
 Interface     Name                Status    Reason             
----------------------------------------------------------------
 Tunnel7       --                  up        no-reason         
 Tunnel8       --                  up        no-reason         
 Tunnel36      --                  up        no-reason         
 Tunnel37      --                  up        no-reason         
 Tunnel38      --                  up        no-reason         
 Tunnel39      --                  up        no-reason         
 Tunnel40      --                  up        no-reason         
 Tunnel41      --                  up        no-reason         
 Tunnel42      --                  up        no-reason         
 Tunnel43      --                  up        no-reason         
 Tunnel44      --                  up        no-reason         
 Tunnel45      --                  up        no-reason         
 Tunnel46      --                  up        no-reason         
 Tunnel47      --                  up        no-reason         

```

**Comment by tahigash** [comment]
Hi @oianson thanks for reporting this issue. I've identified the issue. The fix for the issue will be ready for next release 21.5 (end of May).

And for this kind of parser issue, we are encouraging users to contribute fixes. 
Please consider fixing and contribute from next time if possible.

Some references:
Write a parser
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

Contribution guidelines
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/contribute/contribute.html#contribute

**Comment by tahigash** [comment]
The fix is already merged internally. and the fix will be in pyATS `21.5` (end of May). Closing this issue.
