### ISSUE TITLE
IOS-XR "ping [ip]" parser fails on ping failure

### ISSUE THREAD

**Issue by fordan** [CiscoTestAutomation/genieparser#446]
Executing from the shell: ```pyats parse "ping 204.145.227.1" --testbed-file ping-tb.yml```

I receive the following:
```
Issue with the parser ping 204.145.227.1

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['ping', 'statistics']]
100%|███████████████████████████████████████████████████████████████| 1/1 [00:13<00:00, 13.23s/it]
```

The command succeeds with a pingable address generating the appropriate json.

```
  0%|                                                                       | 0/1 [00:00<?, ?it/s]{
  "ping": {
    "address": "172.16.72.208",
    "data_bytes": 100,
    "repeat": 5,
    "result_per_line": [
      "Mon May 10 14:57:53.988 EDT",
      "!!!!!"
    ],
    "statistics": {
      "received": 5,
      "round_trip": {
        "avg_ms": 1.0,
        "max_ms": 1.0,
        "min_ms": 1.0
      },
      "send": 5,
      "success_rate_percent": 100.0
    },
    "timeout_secs": 2
  }
}
```
Example of the commands run manually on box using CLI:

```
RP/0/RP0/CPU0:x#ping 172.16.72.208
Mon May 10 15:15:25.659 EDT
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 172.16.72.208, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 1/1/1 ms
RP/0/RP0/CPU0:x#ping 204.145.227.1
Mon May 10 15:15:31.278 EDT
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 204.145.227.1, timeout is 2 seconds:
.....
Success rate is 0 percent (0/5)
RP/0/RP0/CPU0:x#
```

System is an ASR 9912 running IOS-XR 6.2.3

**Comment by domachad** [comment]
Hi @fordan, thank you for bringing this matter to our attention.
A fix has been added to the code and will be available in the next release.
