### ISSUE TITLE
IOSXE: "show users" - SchemaMissingKeyError: Missing keys: [['line', '', 'host']]

### ISSUE THREAD

**Issue by oianson** [CiscoTestAutomation/genieparser#458]
The IOSXE "show users" parser is coming back empty with the following data, I assume its because the location (foo-bar.cisco.com) is on a different line. 

```
show users
    Line       User       Host(s)              Idle       Location
*  2 vty 0     admin      idle                 00:00:00
                                                   			 foo-bar.cisco.com
```

When I use the Parser in Robot i get the following error 

```
SchemaMissingKeyError: Missing keys: [['line', '', 'host']] | &nbsp;
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 120, in metaparser_on_device
    return self.metaparser_on_device_alias_context(device=device,
  File "/venv/lib/python3.8/site-packages/genie/libs/robot/GenieRobot.py", line 161, in metaparser_on_device_alias_context
    return con.parse(parser)
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate

```

**Comment by oianson** [comment]
Seems like the output is only on the 2nd line because when unicon connects to the device it  changes the terminal width to 0 and that seems to be causing this... As a quick win I'll just make unicon change it to 254 width

```
D1-INETIU-C9800#show terminal | i idth
Length: 58 lines, Width: 254 columns
D1-INETIU-C9800#show users
    Line       User       Host(s)              Idle       Location
   0 con 0     admin      idle                 00:01:30
   2 vty 0     admin      idle                 00:01:25 ams-oianson-nitro2.cisco.com
*  3 vty 1     admin      idle                 00:00:00 ams-oianson-nitro2.cisco.com

  Interface    User               Mode         Idle     Peer Address

D1-INETIU-C9800#terminal width 0

D1-INETIU-C9800#show terminal | i idth
Length: 58 lines, Width: 0 columns
D1-INETIU-C9800#show users
    Line       User       Host(s)              Idle       Location
   0 con 0     admin      idle                 00:01:45
   2 vty 0     admin      idle                 00:01:39 ams-oianson-nitro2.cisco.com
*  3 vty 1     admin      idle                 00:00:00
                                                    ams-oianson-nitro2.cisco.com

**Comment by domachad** [comment]
Hi @oianson , thank you for the additional information.
We are investigating the issue and we will get back to you as soon as possible.

**Comment by domachad** [comment]
Hi @oianson, it seems like this is a problem with IOSXE.
Since you find a workaround, do you still want us to update the parser? 
In this case, we would change it to work with the default width (80 columns).

**Comment by oianson** [comment]
Hi @domachad 
I think it could be beneficial for the parser to be updated despite the IOSXE issue, there's no urgency at least.

**Comment by domachad** [comment]
Hi @oianson , thank you again for reporting the issue.
A fix was developed and it will be available in the next release.
