### ISSUE TITLE
Show Access Session Interface Details Error with Session timeout:

### ISSUE THREAD

**Issue by dkhenderson2** [CiscoTestAutomation/genieparser#460]
Seeing an issue on iosxe devices parsing the "show access-session interface GigabitEthernetX/X/X details"

If there is a session timeout defined, the parser errors out.

Sample output:

```
show access-session interface GigabitEthernetX/X/X details
            Interface:  GigabitEthernetX/X/X
               IIF-ID:  0x3415B9C7
          MAC Address:  xxxx.xxxx.xxxx
         IPv6 Address:  Unknown
         IPv4 Address:  X.X.X.X
            User-Name:  XX-XX-XX-XX-XX-XX
          Device-type:  IP-Phone
               Status:  Authorized
               Domain:  VOICE
       Oper host mode:  multi-auth
     Oper control dir:  in
      Session timeout:  N/A
    Common Session ID:  1100190A000FCC4B7FD00635
      Acct Session ID:  0x00074143
               Handle:  0x12000d1f
       Current Policy:  PORT_AUTH_POLICY
Local Policies:
         Idle timeout: 60 sec
Server Policies:
              ACS ACL: xACSACLx-IP-Shoretel_Access-5fb3dbb6
Method status list:
       Method           State
        dot1x           Stopped
          mab           Authc Success

----------------------------------------

            Interface:  GigabitEthernetX/X/X
               IIF-ID:  0x3415B9C7
          MAC Address:  xxxx.xxxx.xxxx
         IPv6 Address:  Unknown
         IPv4 Address:  Unknown
            User-Name:  PCNAME@corp.company.com
            User-Role:  Employees
          Device-type:  Microsoft-Workstation
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  in
      Session timeout:  14400s (server), Remaining: 4836s
       Timeout action:  Reauthenticate
    Common Session ID:  1100190A00137D8E6B9F0A97
      Acct Session ID:  0x0009cbfc
               Handle:  0x89000d7f
       Current Policy:  PORT_AUTH_POLICY
Local Policies:
         Idle timeout: 60 sec
Server Policies:
      Session-Timeout: 14400 sec
              ACS ACL: xACSACLx-IP-Employee_Access-5f89fe0c
Method status list:
       Method           State
        dot1x           Authc Success
          mab           Stopped

```
When the Session timeout is anything other then N/A I receive the following error:

```
Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 375, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 349, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 305, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 276, in genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 252, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaTypeError: interfaces.GigabitEthernetX/X/X.mac_address.xxxx.xxxx.xxxx.session_timeout: Expected type '{'type': <class 'str'>, Optional  (str) timeout: <class 'str'>, Optional  (str) remaining: <class 'str'>}' but got type '14400 sec'(<class 'str'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyats_test.py", line 115, in <module>
    get_device_auth_sessions(ip_address)
  File "pyats_test.py", line 86, in get_device_auth_sessions
    f"show access-session interface {interface} details")
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 306, in genie.metaparser._metaparser.MetaParser.parse
Exception: Parser ShowAccessSessionInterfaceDetails schema checking failed
```

**Comment by domachad** [comment]
Hi @dkhenderson2,
thank you for reporting this issue.

Which version are you using? Did you try updating pyats to its latest version?
