### ISSUE TITLE
KeyError: 'vrf' due to missing key in sum_dict when parsing content from "show bgp ipv6 unicast sumary" on IOS-XE 

### ISSUE THREAD

**Issue by apieters-odisee** [CiscoTestAutomation/genieparser#461]
2021-06-03 10:01:38,579: %UNICON-INFO: +++ 02str.pe0 with alias 'cli': executing command 'show bgp ipv6 unicast summary' +++
show bgp ipv6 unicast summary
BGP router identifier 94.140.160.20, local AS number 8368
BGP table version is 2615, main routing table version 2615
33 network entries using 5544 bytes of memory
134 path entries using 13936 bytes of memory
11/11 BGP path/bestpath attribute entries using 1760 bytes of memory
166 BGP rrinfo entries using 3984 bytes of memory
30 BGP AS-PATH entries using 752 bytes of memory
14 BGP community entries using 352 bytes of memory
578 BGP extended community entries using 14064 bytes of memory
0 BGP route-map cache entries using 0 bytes of memory
0 BGP filter-list cache entries using 0 bytes of memory
BGP using 40392 total bytes of memory
BGP activity 150920/135992 prefixes, 1608817/1575019 paths, scan interval 60 secs

Neighbor        V           AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
2001:4C40:0:FFFF:95:171:160:10
                4         8368  113986  122655     2615    0    0 11w0d          67
2001:4C40:0:FFFF:95:171:160:20
                4         8368  111875  122625     2615    0    0 11w0d          67
02str-pe0#
Puree! Something went wrong when trying to collect the output on this device
Traceback (most recent call last):
  File "bgp_neighbor_compare.py", line 106, in <module>
    _bgp_ipv6_output=get_parsed_output(_genie_device,'ipv6','unicast')
  File "bgp_neighbor_compare.py", line 76, in get_parsed_output
    output = device.parse(f'show bgp {afi} {safi} summary')
  File "src/genie/conf/base/device.py", line 543, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/apieters/pyats/pypi/genieparser/src/genie/libs/parser/iosxe/show_bgp.py", line 2330, in cli
    return super().cli(output=show_output, vrf=vrf, rd=rd,
  File "/home/apieters/pyats/pypi/genieparser/src/genie/libs/parser/iosxe/show_bgp.py", line 2210, in cli
    if 'neighbor' not in sum_dict['vrf'][vrf]:
KeyError: 'vrf'

Variable sum_dict does not have this key value. 
For IPv4 this is done in regex match p9 - when coming in the key settings done in IPv4 for this variable, the parsing is OK:

                    neighbor = str(m.groupdict()['neighbor'])
        >>       sum_dict.setdefault('vrf', {}).setdefault(vrf, {})
                    if 'neighbor' not in sum_dict['vrf'][vrf]:

**Comment by lsheikal** [comment]
@apieters-odisee can you clearly define the show command output which you are using? And attach tradelogs as well

**Comment by apieters-odisee** [comment]
hereby a log file that show how a script I use to collect stats with genie parser fails and what correction I added to the genie parse lib. The failure happens , as you will notice in the log below, when collecting "show bgp ipv6 unicast summary"  from a cisco IOS-XE device only 
[devops_local.log](https://github.com/CiscoTestAutomation/genieparser/files/6899091/devops_local.log)

**Comment by lsheikal** [comment]
@apieters-odisee did you add fix to this issue?

**Comment by apieters-odisee** [comment]
yes indeed - similar thing is done on another parse match

**Comment by lsheikal** [comment]
Can you rise PR for that if its fixed?

**Comment by lsheikal** [comment]
```
show bgp ipv6 unicast summary
BGP router identifier 94.140.160.20, local AS number 8368
BGP table version is 2615, main routing table version 2615
33 network entries using 5544 bytes of memory
134 path entries using 13936 bytes of memory
11/11 BGP path/bestpath attribute entries using 1760 bytes of memory
166 BGP rrinfo entries using 3984 bytes of memory
30 BGP AS-PATH entries using 752 bytes of memory
14 BGP community entries using 352 bytes of memory
578 BGP extended community entries using 14064 bytes of memory
0 BGP route-map cache entries using 0 bytes of memory
0 BGP filter-list cache entries using 0 bytes of memory
BGP using 40392 total bytes of memory
BGP activity 150920/135992 prefixes, 1608817/1575019 paths, scan interval 60 secs

Neighbor V AS MsgRcvd MsgSent TblVer InQ OutQ Up/Down State/PfxRcd
2001:4C40:0:FFFF:95:171:160:10
4 8368 113986 122655 2615 0 0 11w0d 67
2001:4C40:0:FFFF:95:171:160:20
4 8368 111875 122625 2615 0 0 11w0d 67
```
This console output seems to work as expected. Can you pull the latest genieparser and test it.

**Comment by apieters-odisee** [comment]
when upgrading to the latest release of pyats and genie, I now get a different python error when executing my script but once more, the error is caused when the BGP AFI ipv6 show  command routine in called. Error seems to be caused by an undeclared variable:
File "/home/apieters/pyats/pypi/genieparser/src/genie/libs/parser/iosxe/show_bgp.py", line 2601, in cli
    if 'address_family' not in nbr_dict:
UnboundLocalError: local variable 'nbr_dict' referenced before assignment
logging collected: [devops_local.log](https://github.com/CiscoTestAutomation/genieparser/files/6906142/devops_local.log)

**Comment by lsheikal** [comment]
can you share the original "show bgp ipv6 unicast summary" command console output without <removed>. So that i can test it out.

**Comment by apieters-odisee** [comment]
![image](https://user-images.githubusercontent.com/68351611/128210038-d780af45-c87b-4998-9924-35c33d40c8d8.png)
fix I added to the genieparser code to get things working once more in my enviroment
