### ISSUE TITLE
[iosxr] Issue with the parser show l2vpn bridge-domain detail

### ISSUE THREAD

**Issue by akaevgen** [CiscoTestAutomation/genieparser#469]
Issue with the parser show l2vpn bridge-domain detail

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/eefimoch/.local/lib/python3.7/site-packages/genie/libs/parser/iosxr/show_l2vpn.py", line 1952, in cli
    **_pw_id_dict = vfi_obj_dict.setdefault('neighbor', {}). \_**
UnboundLocalError: local variable 'vfi_obj_dict' referenced before assignment

**Comment by akaevgen** [comment]
[show_l2vpn_bridge-domain_detail.console.txt](https://github.com/CiscoTestAutomation/genieparser/files/6644561/show_l2vpn_bridge-domain_detail.console.txt)

**Comment by GerriorL** [comment]
Thank you for catching this and providing an example output to work with

**Comment by GerriorL** [comment]
Merged a fix on the internal branch. It should come through on the next release
