### ISSUE TITLE
show interfaces desc -> Parser Output is empty

### ISSUE THREAD

**Issue by kebced** [CiscoTestAutomation/genieparser#47]
Hello

i have a problem when i want parse show interface description:

from genie.conf import Genie
import os

eve='/Users/cedric/Devops/RecetteTechnique/testbed.yaml'
testbed=Genie.init(eve)
rtr = testbed.devices["R1"]
rtr.connect()
out=rtr.execute("show interfaces description")

>>> out=rtr.parse("show interfaces description")
[2019-10-14 11:27:15,352] +++ R1: executing command 'show interfaces description' +++
show interfaces description
Interface                      Status         Protocol Description
Et0/0                          up             up       
Et0/1                          up             up       
Et0/2                          up             up       
Et0/3                          up             up       
Lo0                            up             up       
Vl1                            up             up       
R1#
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 517, in genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 289, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 223, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty

my version : Successfully installed genie.libs.parser-19.9.1b3

my yaml:

testbed:
  name: TESTBED
devices:
  R1:
      os: ios
      type: iou
      connections:
          console:
              protocol: telnet
              ip: 192.168.248.174
              port: 32769

Cedric.

**Comment by jeaubin** [comment]
Hi @kebced 

We will look into it

**Comment by kebced** [comment]
Hi

with iosxe, it's good. i change my testbed.
thx for your help
