### ISSUE TITLE
C881 - Not parsing "show inventory"

### ISSUE THREAD

**Issue by bilalel** [CiscoTestAutomation/genieparser#473]
Hi,

It is not possible to parse the ouput of "show inventory" on a CISCO881G-K9 with IOS Version 15.1(4)M1.

```
2021-06-18 15:43:58,201: %UNICON-INFO: +++ r1 with alias 'cli': executing command 'show inventory' +++
show inventory
NAME: "881G", DESCR: "881G chassis, Hw Serial#: FCZ********, Hw Revision: 1.0"
PID: CISCO881G-K9      , VID: V01 , SN: FCZ********


r1#
Traceback (most recent call last):
  File "connect_cipher.py", line 14, in <module>
    main()
  File "connect_cipher.py", line 9, in main
    p1 = dev.parse('show inventory')
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 290, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 222, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty
```

Best regards,
Bilal

**Comment by danielgraziano** [comment]
Hi @bilalel I just tried with the latest version and it seems to work:
``` python
>>> from genie.conf.base import Device

>>> dev = Device(name='aName', os='ios', platform='')
>>> dev.custom.abstraction = {'order':['os']}
>>> output = """NAME: "881G", DESCR: "881G chassis, Hw Serial#: FCZ********, Hw Revision: 1.0"
... PID: CISCO881G-K9      , VID: V01 , SN: FCZ********"""
>>>
>>> dev.parse('show inventory', output=output)
{'main': {'chassis': {'CISCO881G-K9': {'name': '881G', 'descr': '881G chassis, Hw Serial#: FCZ********, Hw Revision: 1.0', 'pid': 'CISCO881G-K9', 'vid': 'V01 ', 'sn': 'FCZ********'}}}}
```

Can you please verify if you are running the latest version with `pyats version check`. It should be 21.5, if not, please upgrade with `pyats version update`
