### ISSUE TITLE
Issue with parser "show environment all "

### ISSUE THREAD

**Issue by johnnynieves** [CiscoTestAutomation/genieparser#475]
Hi Team,
i use python3.7.10 and i run my app in virtualenv using pipenv. I am having issues with only the above parser all other parsers I use via my app work great. I tried using the genie parse itself see below:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(pyATS_Networking) johnny@Automation-World:~/Projects/Automation/pyATS_Networking$ genie parse "show environment all" --testbed-file Testbed/testbed.yaml --devices Distro
  0%|                                                                                                                | 0/1 [00:00<?, ?it/s]Issue with the parser show environment all

Traceback (most recent call last):
  File "/home/johnny/.local/share/virtualenvs/pyATS_Networking-Wl2N0cVV/lib/python3.7/site-packages/unicon/plugins/generic/service_implementation.py", line 705, in call_service
    self.result = self.get_service_result()
  File "src/unicon/bases/routers/services.py", line 230, in unicon.bases.routers.services.BaseService.get_service_result
unicon.core.errors.SubCommandFailure: ('sub_command failure, patterns matched in the output:', ['^%\\s*[Ii]nvalid (command|input)'], 'service result', "show environment all\r\nshow environment all\r\n        ^\r\n% Invalid input detected at '^' marker.\r\n\r\nDistro#")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/johnny/.local/share/virtualenvs/pyATS_Networking-Wl2N0cVV/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_platform.py", line 3126, in cli
    out = self.device.execute(self.cli_command)
  File "src/unicon/bases/routers/services.py", line 254, in unicon.bases.routers.services.BaseService.__call__
  File "/home/johnny/.local/share/virtualenvs/pyATS_Networking-Wl2N0cVV/lib/python3.7/site-packages/unicon/plugins/generic/service_implementation.py", line 710, in call_service
    raise SubCommandFailure("Command execution failed", err) from err
unicon.core.errors.SubCommandFailure: ('Command execution failed', SubCommandFailure('sub_command failure, patterns matched in the output:', ['^%\\s*[Ii]nvalid (command|input)'], 'service result', "show environment all\r\nshow environment all\r\n        ^\r\n% Invalid input detected at '^' marker.\r\n\r\nDistro#"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 275, in genie.metaparser._metaparser.MetaParser.parse
genie.metaparser.util.exceptions.InvalidCommandError: Invalid command has been executed
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.29it/s]

(pyATS_Networking) johnny@Automation-World:~/Projects/Automation/pyATS_Networking$ 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I get the same issue if I run the pyats parse version:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(pyATS_Networking) johnny@Automation-World:~/Projects/Automation/pyATS_Networking$ pyats parse "show environment all" --testbed-file Testbed/testbed.yaml --devices Distro
  0%|                                                                                                                | 0/1 [00:00<?, ?it/s]Issue with the parser show environment all

Traceback (most recent call last):
  File "/home/johnny/.local/share/virtualenvs/pyATS_Networking-Wl2N0cVV/lib/python3.7/site-packages/unicon/plugins/generic/service_implementation.py", line 705, in call_service
    self.result = self.get_service_result()
  File "src/unicon/bases/routers/services.py", line 230, in unicon.bases.routers.services.BaseService.get_service_result
unicon.core.errors.SubCommandFailure: ('sub_command failure, patterns matched in the output:', ['^%\\s*[Ii]nvalid (command|input)'], 'service result', "show environment all\r\nshow environment all\r\n        ^\r\n% Invalid input detected at '^' marker.\r\n\r\nDistro#")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/johnny/.local/share/virtualenvs/pyATS_Networking-Wl2N0cVV/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_platform.py", line 3126, in cli
    out = self.device.execute(self.cli_command)
  File "src/unicon/bases/routers/services.py", line 254, in unicon.bases.routers.services.BaseService.__call__
  File "/home/johnny/.local/share/virtualenvs/pyATS_Networking-Wl2N0cVV/lib/python3.7/site-packages/unicon/plugins/generic/service_implementation.py", line 710, in call_service
    raise SubCommandFailure("Command execution failed", err) from err
unicon.core.errors.SubCommandFailure: ('Command execution failed', SubCommandFailure('sub_command failure, patterns matched in the output:', ['^%\\s*[Ii]nvalid (command|input)'], 'service result', "show environment all\r\nshow environment all\r\n        ^\r\n% Invalid input detected at '^' marker.\r\n\r\nDistro#"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 275, in genie.metaparser._metaparser.MetaParser.parse
genie.metaparser.util.exceptions.InvalidCommandError: Invalid command has been executed
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.32it/s]

(pyATS_Networking) johnny@Automation-World:~/Projects/Automation/pyATS_Networking$ 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I also tried to fix this issue by uninstalling libraries and destroying my virtual environment and starting fresh thinking perhaps Im the issue however i still get the issue. I tried it on 3 different laptops running linux to no avail. Any assistance would be great. Thanks!!

**Comment by LukasMcClelland** [comment]
Hi @johnnynieves 

Apologies for the delay! 

This looks like it might not be related to the actual parser, but could be caused from something like configuration. 

If you visit https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers you're able to see which parsers we currently have.

![image](https://user-images.githubusercontent.com/33130026/124513479-e9b30580-dda8-11eb-9993-11e4b4addc54.png)

What type of OS are you trying to run this show command on? Looks like "show environment all" is only available for IOS and IOSXE

**Comment by johnnynieves** [comment]
Hello Thank you for your reply. I heavily use t https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers . I am using "show environment all" parser on IOSXE on 3850s. I can use all the other parsers just fine. I follow the traceback and it points to the below:
Traceback (most recent call last):
File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
File "src/genie/metaparser/_metaparser.py", line 275, in genie.metaparser._metaparser.MetaParser.parse
genie.metaparser.util.exceptions.InvalidCommandError: Invalid command has been executed

I eliminated my python code and use the parser manually in the command line and i get the above result. I also used 3 other laptops with linux and i get the same error. Any ideas would be greatly appreciated.

**Comment by LukasMcClelland** [comment]
Hello Johnny, thank you for providing that information. Would it be possible for you to share you testbed file? If not, then please ensure that you've specified the platform correctly within your testbed file (ie.`platform: c3850`)

**Comment by LukasMcClelland** [comment]
Quick update, we'll be adding in some new `show env` parsers for IOSXE in the near future. It's very likely that adding these parsers will provide a work around for this situation. I'll close this issue for now but you can still provide information here if you feel that it will help to identify the issue

Thank you, 
Lukas
