### ISSUE TITLE
NX-OS show interface parser can't handle "Hardware failure" state and parser logic

### ISSUE THREAD

**Issue by eoprede** [CiscoTestAutomation/genieparser#485]
Hello,

I have Nexus switch with one of the interfaces in Hardware error status, like this: 
```
Ethernet1/1 is down (Hardware failure)
 Dedicated Interface
```

The parser can not parse it out and code execution fails with error:
```
Issue with the parser show interface

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/usr/local/lib/python3.7/site-packages/genie/libs/parser/nxos/show_interface.py", line 580, in cli
    interface_dict[interface]['dedicated_interface'] = True
KeyError: ''
```

Now, the solution to the problem is very basic - one just needs to add r'(\(Hardware\s+failure\))?' to p1 = re.compile statement.

There is, however, a much larger issue present: the only reason I was able to catch this error is because I got the very 1st interface in hardware failure state. If I had interface Eth1/2 with hardware failure state, the code would simply continue executing and will override Eth1/1 values with values from Eth1/2 interface. I am not sure what's the best solution to the problem, but in the current state I can't be 100% sure that the values I receive from the pyats are accurate and data is not mixed up between interfaces.

**Comment by LukasMcClelland** [comment]
Hello @eoprede, thank you for letting us know about this issue. Myself or another engineer will create a fix for this

**Comment by LukasMcClelland** [comment]
Just letting you know that this has been fixed and will be in next week's release
