### ISSUE TITLE
Junos - "show interfaces" - UnboundLocalError "address_family_dict"

### ISSUE THREAD

**Issue by Kani999** [CiscoTestAutomation/genieparser#515]
Hello,

The parser `show interfaces` for my device with OS `junos`  fails with the following error

```
2021-08-26 13:11:56,869: %UNICON-INFO: connection to device
--- JUNOS 15.1R4.6 built 2016-06-23 21:29:57 UTC
2021-08-26 13:12:01,698: %UNICON-INFO: +++ device with alias 'cli': executing command 'show interfaces' +++
show interfaces
Physical interface: ge-0/0/0, Enabled, Physical link is Up
  Interface index: 130, SNMP ifIndex: 502
.
.   Interfaces output
.

Physical interface: vme, Enabled, Physical link is Down
.
.   Interfaces output
.
{master:0}
user@device >

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    p1 = dev.parse('show interfaces')
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 550, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/jankrupa/.local/lib/python3.8/site-packages/genie/libs/parser/junos/show_interface.py", line 1962, in cli
    address_family_flags_dict = address_family_dict.setdefault('address-family-flags', {})
UnboundLocalError: local variable 'address_family_dict' referenced before assignment
```

**Comment by tahigash** [comment]
@Kani999, thanks for reporting the issue. genie parser is open-sourced. so we are encouraging users to contribute fixes/enhancement like above. can you consider contributing above fix?

references:
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html
https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/contribute/contribute.html#contribute

**Comment by tahigash** [comment]
thanks for opening the PR and contribution! We now can track on the PR. So, I'm closing this issue. but feel free to open when needed.
