### ISSUE TITLE
Bug in 'show policy-map interface {interface}' for IOS-XR

### ISSUE THREAD

**Issue by avgvstoSilva** [CiscoTestAutomation/genieparser#596]
Found this issue for genieparser == 2.10, haven't tried any other releases.

I've found an Issue with the command 'show policy-map interface {interface}' for IOS XR Devices. I first attempted get the parsed config on a production environment, later went on to the DevNet Sandbox Lab for IOSXR (always-on lab) to debug on a simulated environment. The output format I'm trying to parse is the following:

```
RP/0/RP0/CPU0:iosxr1#show policy-map interface GigabitEthernet 0/0/0/6
Wed Dec 15 13:26:20.118 UTC
GigabitEthernet0/0/0/6 direction input: Service Policy not installed

GigabitEthernet0/0/0/6 output: p1

Class class-default
  Classification statistics          (packets/bytes)     (rate - kbps)
    Matched             :                   0/0                    0
    Transmitted         :                   0/0                    0
    Total Dropped       :                   0/0                    0
  Queueing statistics
    Queue ID                             : 56
    High watermark                       : N/A
    Inst-queue-len                       : N/A
    Avg-queue-len                        : N/A
    Taildropped(packets/bytes)           : 0/0
    Queue(conform)      :                   0/0                    0
    RED random drops(packets/bytes)      : 0/0

RP/0/RP0/CPU0:iosxr1#
```
I configured a policy-map so I could emulate real configuration and I realized that whenever a class-map is defined (the message for the given direction is not "Service Policy not installed") the parser is not able to get the detailed statistics (such as matched, transmitted, etc) and the resulting output is empty.

If I try the parser with an empty policy-map configuration for the given interface, I do get output as expected, so I suspect some regex matching in optional fields may be the cause of this error.

```python
Wed Dec 15 13:42:23.977 UTC
GigabitEthernet0/0/0/5 direction input: Service Policy not installed
GigabitEthernet0/0/0/5 direction output: Service Policy not installed
RP/0/RP0/CPU0:iosxr1#
{'interface': {'GigabitEthernet0/0/0/5': {'service_policy': {'input': {'policy_status': 'Service Policy not installed'}, 'output': {'policy_status': 'Service Policy not installed'
```

Here's the error message I get if any service policy is installed:

```python
RP/0/RP0/CPU0:iosxr1#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 524, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 279, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/augustus/.local/lib/python3.8/site-packages/genie/libs/parser/iosxr/show_policy_map.py", line 210, in cli
    class_dict = name_dict.setdefault('class', {}).\
UnboundLocalError: local variable 'name_dict' referenced before assignment
```

My testbed file is pointing to the always-on cisco devnet sandbox for IOSXR (credentials are public so I'm sharing the full file here).

```yaml
devices:
  iosxr1:
    connections:
      cli:
        ip: sandbox-iosxr-1.cisco.com
        port: 22
        protocol: ssh
    credentials:
      default:
        password: C1sco12345
        username: admin
      enable:
        password: C1sco12345
    os: iosxr
    type: iosxr
```

Here's the script I ran for these tests:

```python
from genie import testbed
from genie.utils.diff import Diff
from genie.libs.parser.utils import get_parser_exclude
tb = testbed.load('testbed.yaml')
device = tb.devices['iosxr1']
device.connect()
output = device.parse('show policy-map interface GigabitEthernet0/0/0/6')

print(output)
```

**Comment by LukasMcClelland** [comment]
Hello and my apologies for not getting to your issue sooner! 

This issue seems to have slipped through the cracks, but rest assured I'm aware of it now and will be working on this

**Comment by LukasMcClelland** [comment]
A fix for this has been merged and will be included in the next release of Genie. Thanks again
