### ISSUE TITLE
ImportError: cannot import name 'ListOf' from 'genie.metaparser.util.schemaengine'

### ISSUE THREAD

**Issue by reddy-t** [CiscoTestAutomation/genieparser#627]
Hello,

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from sea_genie_parser import SEA_Genie
  File "/home/surendra/SEA/Premigration_APIs/sea_genie_parser.py", line 13, in <module>
    from genie.libs.parser.iosxe.show_license import ShowLicense # show licence for iosxe
  File "/home/surendra/SEA/sea_venv/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_license.py", line 22, in <module>
    from genie.metaparser.util.schemaengine import Any, Optional, Or, ListOf
**ImportError: cannot import name 'ListOf' from 'genie.metaparser.util.schemaengine'** (/home/surendra/SEA/sea_venv/lib/python3.7/site-packages/genie/metaparser/util/schemaengine.cpython-37m-x86_64-linux-gnu.so)

What went wrong here?

**Comment by muhammad-rafi** [comment]
[reddy-t](https://github.com/reddy-t), I dont see an issue in 3.7, I tested and it worked fine, can you please test like this below ? or if this doesnt work, try re-installing the pyats 'pip install pyats[full]

```
Python 3.7.12 (default, Oct 22 2021, 17:50:30) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from genie.metaparser.util.schemaengine import Any, Optional, Or, ListOf
>>> schema = {
Optional('load_time'): str,
Optional('one_minute'): str,
Optional('five_minutes'): str,
Optional('ntp_time'): str,
Optional('no_eventlog_found'): bool,
Optional('event_log'): ListOf(
    {'log_message': str}
)
}
>>> 
```
