### ISSUE TITLE
'show snmp' iosxe throwing schema error 'Missing keys: [['contact']]' when contact is not configured

### ISSUE THREAD

**Issue by muhammad-rafi** [CiscoTestAutomation/genieparser#635]
I was running this 'show snmp' parser for iosxe and found that, if 'contact' is not configured under snmp configuration, it will throw the SchemaMissingKeyError for the 'contact'. I have found the issue in the current schema, 'contact' key should be an optional key but it is not currently, please see below, I will be raising pull request soon and link this issue. But wanted to raise this, in case, someone may come up with this issues in the mean time. 

Current Schema for the 'contact' key. 
```
    schema = {
        "chassis": str,
        "contact": str,
        Optional("location"): Optional(str),
------------<truncated>--------------

```

Error 
```
Traceback (most recent call last):
  File "iosxe_test.py", line 15, in <module>
    output = device.parse('show snmp')
  File "src/genie/conf/base/device.py", line 527, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 563, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 561, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 312, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 292, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 415, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['contact']]
```

Fix will be 
```
    schema = {
        "chassis": str,
        Optional("contact"): str,
        Optional("location"): Optional(str),
------------<truncated>--------------
```

I also notice that, we may not need Optional(str) for the 'location' and it can be simply 'str', please let me know if like me to include in the pull request.

**Comment by lsheikal** [comment]
Thank you for your contribution. The fix is merged.
