### ISSUE TITLE
ios-xe show track issue

### ISSUE THREAD

**Issue by derevk0** [CiscoTestAutomation/genieparser#662]
Hi Team,

Issue with the genie parser 22.3 for ios-xe "show track" command
Error below:

`Traceback (most recent call last):
  File "csv_track.py", line 138, in <module>
    output_dict = dev.parse('show track', output=track_str2)
  File "src/genie/conf/base/device.py", line 527, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 573, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 279, in genie.metaparser._metaparser.MetaParser.parse
  File "/HOME/1234567/pyats/lib64/python3.6/site-packages/genie/libs/parser/iosxe/show_track.py", line 130, in cli
    type_dict['state'] = group['state']
UnboundLocalError: local variable 'type_dict' referenced before assignment`

Thanks for support.

**Comment by Taarini** [comment]
Hi 

Can you share the device output for show track.

**Comment by derevk0** [comment]
Hi,
Here you go:
`Host> show track 34

Track 34
  IP SLA 34 state
  State is Up
    11 changes, last change 1d16h
  Latest operation return code: OK
  Latest RTT (millisecs) 16`

**Comment by Taarini** [comment]
Thank you will check and get back to you

**Comment by Taarini** [comment]
@derevk0 The issue has been fixed and will be available in the next release.
