### ISSUE TITLE
show hsrp detail - empty parser

### ISSUE THREAD

**Issue by fazlan645292** [CiscoTestAutomation/genieparser#683]
```
>>> dev.parse("show hsrp detail")

2022-07-15 11:45:18,772: %UNICON-INFO: +++ TB-1 with via 'cli': executing command 'show hsrp detail' +++
show hsrp detail
Fri Jul 15 19:45:18.957 MYT
RP/0/RSP0/CPU0:TB-1#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 528, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 567, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 565, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 329, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 233, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty
```

"show hsrp detail" on asr9k/iosxr

**Comment by Taarini** [comment]
Hi 

Did you check manually whether you are getting the expected result for the `show hsrp detail`

**Comment by fazlan645292** [comment]
Hi, 
show hsrp detail returns no output on some devices, which resulted to parser error above.

**Comment by Taarini** [comment]
Can you please share the device output for which you are facing issue and also the OS and platform details

**Comment by fazlan645292** [comment]
I am sorry I dont get your question. but for devices with actual output from the command returns parsed output. Otherwise, the parser error.

**Comment by Taarini** [comment]
Will check with the team and get back to you on this

**Comment by fazlan645292** [comment]
Hi, 

I did several reinstall of pyats and genieparser, couldnt really explain how, maybe I missed something. but this time seems to be working?

2022-07-16 08:30:06,033: %UNICON-INFO: +++ TB-UER-1 with via 'cli': executing command 'show hsrp detail' +++
show hsrp detail
Sat Jul 16 16:30:06.224 MYT
RP/0/RSP0/CPU0:TB-UER-1#
{'No HSRP': {}}

genie==22.6
genie.libs.clean==22.6
genie.libs.conf==22.6
genie.libs.filetransferutils==22.6
genie.libs.health==22.6
genie.libs.ops==22.6
genie.libs.parser==22.6
genie.libs.robot==22.6
genie.libs.sdk==22.6
genie.telemetry==22.6
genie.trafficgen==22.6
pyats==22.6
pyats.aereport==22.6
pyats.aetest==22.6
pyats.async==22.6
pyats.connections==22.6
pyats.contrib==22.6
pyats.datastructures==22.6
pyats.easypy==22.6
pyats.kleenex==22.6
pyats.log==22.6
pyats.reporter==22.6
pyats.results==22.6
pyats.robot==22.6
pyats.tcl==22.6
pyats.topology==22.6
pyats.utils==22.6




Thanks and regards.
