### ISSUE TITLE
bigip parser fails on Device' object has no attribute 'log'

### ISSUE THREAD

**Issue by LucRobalo** [CiscoTestAutomation/genieparser#695]
while trying to add our f5 infrastructure to our pyats tests, we encounter the following error :
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/genie/cli/commands/parser.py", line 265, in genie.cli.commands.parser.ParserCommand.run
  File "src/genie/cli/commands/parser.py", line 302, in genie.cli.commands.parser.ParserCommand.parse
  File "src/pyats/topology/device.py", line 559, in pyats.topology.device.Device.__getattr__
AttributeError: 'Device' object has no attribute 'log'

the connection to the F( device is ok, the testbed is ok as well and we installed the rest connected python module. how can we fix this ?

**Comment by stevedhn** [comment]
Hi, can you provide us the device output, as well the commands you used?

**Comment by LucRobalo** [comment]
Command used : genie parse "/mgmt/tm/sys/management-ip" --testbed-file testbed/f5.yml --output genie_learn_f5_ssl -vvvv
Bydevice you mean the device definition in the testbed ?
devices:
    F5:
      alias: xxxx
      type: bigip
      os: bigip
      custom:
        abstraction:
          order: [os]
      connections:
        rest:
          class: rest.connector.Rest
          ip: xxxxx
          #protocol: https
          port: 443
      credentials:
        rest:
          username: admin
          password: xxxx
