### ISSUE TITLE
IOS show inventory UnboundLocalError: local variable 'slot_dict' on CISCO7606

### ISSUE THREAD

**Issue by dirkf98** [CiscoTestAutomation/genieparser#705]
Hello,

I have a problem with the parser for IOS for show inventory.
When using it on a CISCO7606 it fails with the error message "`UnboundLocalError: local variable 'slot_dict' referenced before assignment`"

I wanted to fix it myself but I'm not sure at wich file I need to look.
In the stack trace I see that the error is in file `genie/libs/parser/ios/show_platform.py`.
Based on the platform definition in the testbed I expected that the parser in `genie/libs/parser/ios/c7600/show_platform.py` is used.
Which is basically a reference to `genie/libs/parser/ios/cat6k/show_platform.py`.

I'm not sure if there is something wrong with the platform definition. Can you help me out?

I'm using Genie 22.7

My testbed dict is created dynamically and looks like this:
`{"devices": {"test_c7606_1": {"os": "ios", "platform": "c7600", "connections": {"cli": {"protocol": "ssh", "ip": "192.168.1.1", "arguments": {"learn_hostname": true, "learn_os": true}, "settings": {"EXEC_TIMEOUT": 180}}}, "credentials": {"default": {"username": "some_user", "password": "*****"}, "enable": {"password": "*****"}}}}, "testbed": {"name": ""}, "topology": {}}`

The complete stack trace:
```
Traceback (most recent call last):
  File "src/genie/conf/base/device.py", line 528, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 567, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 565, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/ggcniansible/py_venvs/genie-22.7/lib64/python3.9/site-packages/genie/libs/parser/ios/show_platform.py", line 304, in cli
    subslot_dict = slot_dict\
UnboundLocalError: local variable 'slot_dict' referenced before assignment
```

And this is the output for `show inventory` on the router:
```
NAME: "CISCO7606", DESCR: "Cisco Systems Cisco 7600 6-slot Chassis System"
PID: CISCO7606         , VID:    , SN: BLABLABLABL

NAME: "CLK-7600 1", DESCR: "OSR-7600 Clock FRU 1"
PID: CLK-7600          , VID:    , SN: BLABLABLABL

NAME: "CLK-7600 2", DESCR: "OSR-7600 Clock FRU 2"
PID: CLK-7600          , VID:    , SN: BLABLABLABL

NAME: "module 1", DESCR: "WS-X6408A-GBIC 8 port 1000mb GBIC Enhanced QoS Rev. 3.1"
PID: WS-X6408A-GBIC    , VID:    , SN: BLABLABLABL

NAME: "Transceiver Gi1/1", DESCR: "Transceiver 1000BaseSX Gi1/1"
PID: N/A               , VID: 01  , SN: BLABLABLABL     

NAME: "module 5", DESCR: "WS-SUP720-3BXL 2 ports Supervisor Engine 720 Rev. 5.8"
PID: WS-SUP720-3BXL    , VID: V07, SN: BLABLABLABL

NAME: "msfc sub-module of 5", DESCR: "WS-SUP720 MSFC3 Daughterboard Rev. 3.3"
PID: WS-SUP720         , VID:    , SN: BLABLABLABL

NAME: "switching engine sub-module of 5", DESCR: "WS-F6K-PFC3BXL Policy Feature Card 3 Rev. 1.10"
PID: WS-F6K-PFC3BXL    , VID: V02, SN: BLABLABLABL

NAME: "module 6", DESCR: "WS-SUP720-3BXL 2 ports Supervisor Engine 720 Rev. 5.2"
PID: WS-SUP720-3BXL    , VID: V07, SN: BLABLABLABL

NAME: "msfc sub-module of 6", DESCR: "WS-SUP720 MSFC3 Daughterboard Rev. 2.5"
PID: WS-SUP720         , VID:    , SN: BLABLABLABL

NAME: "switching engine sub-module of 6", DESCR: "WS-F6K-PFC3BXL Policy Feature Card 3 Rev. 1.8"
PID: WS-F6K-PFC3BXL    , VID: V01, SN: BLABLABLABL

NAME: "PS 1 PWR-2700-AC", DESCR: "AC power supply, 2700 watt 1"
PID: PWR-2700-AC       , VID: V02, SN: BLABLABLABL

NAME: "PS 2 PWR-2700-AC", DESCR: "AC power supply, 2700 watt 2"
PID: PWR-2700-AC       , VID: V02, SN: BLABLABLABL
```

**Comment by Taarini** [comment]
The parser is working fine please add the below in your testbed file,

```
    custom:
      abstraction:
        order: [os, platform]
```

**Comment by dirkf98** [comment]
Thanks a lot. That did the trick.
