### ISSUE TITLE
iosxe - ShowCryptoSession SchemaMissingKeyError 

### ISSUE THREAD

**Issue by awk5303** [CiscoTestAutomation/genieparser#724]
(22.11) 12:39:49-apieters@as8368-netdevops-vm:~ $ genie parse "show crypto session" --testbed-file /home/apieters/pyats/SRC/INPUT/TOPOLOGY/UAT/cml_testbed.yaml --device virl.aal1-dmvpn 
  0%|                                                                                                                                                                         | 0/1 [00:00<?, ?it/s]Issue with the parser show crypto session

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 531, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 568, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['interface', 'Tunnel3111', 'peer']]

Current parsing mechanism is not taking into account that the show command output could have a repetition on the same interface name.
virl.aal1-dmvpn#show crypto session
_Crypto session current status

**Interface: Tunnel3111**
Session status: DOWN
Peer: 192.168.1.1 port 500 
  IPSEC FLOW: permit ip 100.75.0.0/255.255.255.192 192.168.25.0/255.255.255.128 
        Active SAs: 0, origin: crypto map
  IPSEC FLOW: permit ip host 100.74.10.1 192.168.25.0/255.255.255.128 
        Active SAs: 0, origin: crypto map

**Interface: Tunnel3111**
Profile: ISAKMP-inner-LOC_A
Session status: DOWN-NEGOTIATING
Peer: 192.168.1.1 port 500 
  Session ID: 0  
  IKEv1 SA: local 94.140.184.80/500 remote 192.168.1.1/500 Inactive 
  Session ID: 0  
  IKEv1 SA: local 94.140.184.80/500 remote 192.168.1.1/500 Inactive_ 

show_crypto.py (parser in IOSXE)
            #Interface: Tunnel0
            m1= p1.match(line)
            if m1:
                groups=m1.groupdict()
                crypto_session_dict[groups['interface_name']]={}
                interface_dict=crypto_session_dict[groups['interface_name']]

crypto_session_dict is taking the 'interface name' as key. This means that upon the second iteration where line="Interface: Tunnel3111" the first instance is getting overwritten leading to an error eventually.

**Comment by Taarini** [comment]
Hi

As you know, genieparser is community driven, I would like you to create a PR with the potential fix that helps to fix this. Let me know if you need any help in this process.

**Comment by awk5303** [comment]
> Hi
> 
> As you know, genieparser is community driven, I would like you to create a PR with the potential fix that helps to fix this. Let me know if you need any help in this process.

PR released: [https://github.com/CiscoTestAutomation/genieparser/pull/725]

**Comment by Taarini** [comment]
Hi 

Thanks for your contribution. We will follow up on getting the PR merged.

**Comment by Taarini** [comment]
Hi @awk5303 

There is a version mismatch which caused the pipeline to fail. Can you please update your code

**Comment by Taarini** [comment]
Hi

Can you please update your pyats. It should fix the issue the jenkins issue

**Comment by awk5303** [comment]
I will add the fix underneath 23.02 and resubmit the code
