### ISSUE TITLE
Could not learn features on ASR1K

### ISSUE THREAD

**Issue by lsullivan1980** [CiscoTestAutomation/genieparser#732]
Hi,
I am getting could not learn feature ospf, bgp, interface errors.  Tracebacks below.

OSPF:
Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/ops/ospf/iosxe/ospf.py", line 1017, in learn
    self.make(final_call=True)
  File "/usr/local/lib/python3.10/dist-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Show Command: show ip ospf neighbor detail
Missing keys: [['vrf', 'default', 'address_family', 'ipv4', 'instance', '7', 'areas', '0.0.0.0', 'interfaces', 'TenGigabitEthernet0/1/4.538', 'neighbors', '10.50.238.2', 'priority'], ['vrf', 'default', 'address_family', 'ipv4', 'instance', '7', 'areas', '0.0.0.0', 'interfaces', 'TenGigabitEthernet0/1/4.538', 'neighbors', '10.50.238.2', 'state']]

BGP:
Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/ops/bgp/iosxe/bgp.py", line 828, in learn
    self.make(final_call=True)
  File "/usr/local/lib/python3.10/dist-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/parser/iosxe/show_bgp.py", line 5903, in cli
    return super().cli(output=show_output, neighbor=neighbor,
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/parser/iosxe/show_bgp.py", line 5764, in cli
    if prefix not in af_dict['received_routes']:
UnboundLocalError: local variable 'prefix' referenced before assignment

INTERFACE:
Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 365, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/ops/interface/iosxe/interface.py", line 346, in learn
    self.make(final_call=True)
  File "/usr/local/lib/python3.10/dist-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/usr/local/lib/python3.10/dist-packages/genie/libs/parser/iosxe/show_interface.py", line 3058, in cli
    ret_dict[intf]['joined_group_addresses'] = sorted(joined_group)
UnboundLocalError: local variable 'intf' referenced before assignment

DEVICE:
"os": "IOS-XE",
    "platform": "ASR1000",
    "processor_type": "2KH",
    "rom": "IOS-XE ROMMON",
    "rtr_type": "ASR1K",
    "system_image": "bootflash:asr1000-universalk9.17.03.04a.SPA.bin",
    "version": "17.3.4a",
    "version_short": "17.3",
    "xe_version": "17.03.04a"

TESTBED:
  ASR_A:
    connections:
      cli:
        ip: x.x.x.x
        protocol: ssh
    credentials:
      default:
        password: '%ASK{}'
        username:user
      enable:
        password: pass
    os: iosxe
    type: router
    platform: asr1k

  ASR_B:
    connections:
      cli:
        ip: x.x.x.x
        protocol: ssh
    credentials:
      default:
        password: '%ASK{}'
        username: user
      enable:
        password: pass
    os: iosxe
    type: router
    platform: asr1k

**Comment by lsullivan1980** [comment]
Removed "platform" and it works now.
