### ISSUE TITLE
EIGRP Topology for nxos Not Found

### ISSUE THREAD

**Issue by vishnuo-lab** [CiscoTestAutomation/genieparser#753]
When i run "shoip eigrp topology {vrf}" for nxos it giving an error saying that its not found.

Could not find parser for 'show ip eigrp topology'  Details: Could not find 
parser for show ip eigrp topology under ('nxos',)

**Comment by iamsatyanarayan** [comment]
Thanks for reaching out piestack support team, I will be looking at your ticket and reviewing it . Please make sure add the logs / pyats version / package list .
Recommend is to always use the latest pyats version (i.e. Current released version 23.3)

**Comment by iamsatyanarayan** [comment]
Thanks for reaching out piestack support team, I will be looking at your ticket and reviewing it . Please make sure add the logs / pyats version / package list .
Recommend is to always use the latest pyats version (i.e. Current released version 23.3)

**Comment by iamsatyanarayan** [comment]
Hi,
'show ip eigrp topology' parser is available . please check :-
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_eigrp.py#L532

**Comment by iamsatyanarayan** [comment]
Hi,
Did you checkout this below link:-
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_eigrp.py#L532

**Comment by iamsatyanarayan** [comment]
Hi,
As we haven't heard back from you , we will be closing this ticket. If you still require further assistance, please feel free to open a new ticket.

**Comment by vishnuo-lab** [comment]
Sorry for the late reply. Its there but gives me error when i run the parser.

Sent from my iPhone

On Jun 8, 2023, at 1:12 AM, iamsatyanarayan ***@***.***> wrote:

﻿

Hi,
As we haven't heard back from you , we will be closing this ticket. If you still require further assistance, please feel free to open a new ticket.

**Comment by vishnuo-lab** [comment]
I put the output in the ticket. But is there some additional thing i should run? More verbose? I am running the parse on the cli.

Sent from my iPhone

On Jun 8, 2023, at 6:30 AM, iamsatyanarayan ***@***.***> wrote:

﻿

Hi,
Can you share with me the trade log ?

**Comment by iamsatyanarayan** [comment]
Hi vishnuo,
You can find the parser for 'show ip eigrp topology' under genieparser. To use that api you have to call like below as
device.parse('show ip eigrp topologyshow ip eigrp topology {vrf}').
You can pass the vrf id as device.parse(f'show ip eigrp topologyshow ip eigrp topology {<pass_the_vrf_id>}').  Please try to use in this way.

**Comment by iamsatyanarayan** [comment]
Hi
We are working on your issue. we will update you.

**Comment by iamsatyanarayan** [comment]
Hi  vishnuo,,
This issue is fixed, you can try now "show ip eigrp topology" parse command.

**Comment by vishnuo-lab** [comment]
I got another exception shown below. I am running version 23.9:

Issue with the parser sho ip eigrp topology vrf internet

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 531, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 568, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/volaganathan/Python_Virtual/Sandbox/lib64/python3.9/site-packages/genie/libs/parser/nxos/show_eigrp.py", line 551, in cli
    return super().cli(output=output)
  File "/home/volaganathan/Python_Virtual/Sandbox/lib64/python3.9/site-packages/genie/libs/parser/nxos/show_eigrp.py", line 519, in cli
    .setdefault(route, {}) \
UnboundLocalError: local variable 'route' referenced before assignment
