### ISSUE TITLE
traceroute - sdwan device

### ISSUE THREAD

**Issue by pmraz123** [CiscoTestAutomation/genieparser#776]
Hello, many sdwan related commands works, but from some reasons traceroute vrf im getting error when I test in pyATS. 

It is there a way how to get output of traceroute in parse format (pandas for example), traceroute vrf the same. 
For example ping works well, also ping vrf IP works well, but when I did ping IP repeat 10 ...that one is not parsed. 

Thank you for avise! 

>>> parsed_output = device.parse('traceroute vrf Mgmt-intf 198.18.7.10')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 529, in genie.conf.base.device.Device.parse
  File "/home/pm7625/.local/lib/python3.10/site-packages/genie/libs/parser/utils/common.py", line 285, in get_parser
    raise ParserNotFound(command, lookup._tokens)
genie.libs.parser.utils.common.ParserNotFound: Could not find parser for traceroute vrf Mgmt-intf 198.18.7.10 under ('iosxe', 'sdwan', None)
>>>

**Comment by kameswararaot** [comment]
Hi pmraz123,

I am working on this issue. Can you please elaborate the issue?

**Comment by kameswararaot** [comment]
Hi pmraz123,

Could you please share the output of the traceroute?

**Comment by kameswararaot** [comment]
Hi pmraz123,

If you still facing this issue, Please share me the output of the traceroute.

**Comment by kameswararaot** [comment]
Hi pmraz123,

Please share me the output of the traceroute. If you still facing this issue.

**Comment by kameswararaot** [comment]
Hi pmraz123,

Since you have not responded, I am closing this ticket. I hope you no longer encounter this issue, but if you are still experiencing the same problem, please let me know, and I will reopen the ticket.
