### ISSUE TITLE
show sdwan control connections - Parser Output is empty

### ISSUE THREAD

**Issue by pmraz123** [CiscoTestAutomation/genieparser#777]
I have up to date version (23.7) - all packages. 

>>> parsed_output = device.parse('show sdwan control connections')

2023-08-07 16:48:23,462: %UNICON-INFO: +++ cat8K_robot1 with via 'a': executing command 'show sdwan control connections' +++
show sdwan control connections
                                                                                       PEER                                          PEER                                          CONTROLLER 
PEER    PEER PEER            SITE       DOMAIN PEER                                    PRIV  PEER                                    PUB                                           GROUP      
TYPE    PROT SYSTEM IP       ID         ID     PRIVATE IP                              PORT  PUBLIC IP                               PORT  ORGANIZATION            LOCAL COLOR     PROXY STATE UPTIME      ID         
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
vsmart  dtls 1.1.1.5         4294950463 1      10.0.5.64                               12346 34.250.253.50                           12346 SDWAN-VIPTELA - 249781  custom1         No    up     24:22:07:45 0           
vsmart  dtls 1.1.1.4         4294950464 1      10.0.2.163                              12346 52.28.233.22                            12346 SDWAN-VIPTELA - 249781  custom1         No    up     17:08:27:45 0           
vmanage dtls 1.1.1.6         4294950465 0      10.0.2.33                               12746 3.123.213.130                           12746 SDWAN-VIPTELA - 249781  custom1         No    up     17:08:28:03 0           

cat8K_robot1#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 531, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 568, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 329, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 233, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty

**Comment by ParimiNeeraja** [comment]
I will be working on your ticket. So, kindly give me some time to analyze the issue.

**Comment by ParimiNeeraja** [comment]
Hello @pmraz123 ,

This fix will reflected with next release.

**Comment by ParimiNeeraja** [comment]
Hello @pmraz123 ,

As i above said it will reflect in next release, if not please reopen this issue

**Comment by ParimiNeeraja** [comment]
Hello @pmraz123 ,

As above said this fix will reflected in next release, if not please reopen this issue.

I fix this issue as below

`{'local_color': {'custom1': {'peer_system_ip': {'1.1.1.5': {'peer_type': 'vsmart', 'peer_protocol': 'dtls', 'site_id': '4294950463', 'domain_id': '1', 'peer_private_ip': '10.0.5.64', 'peer_private_port': '12346', 'peer_public_ip': '34.250.253.50', 'peer_public_port': '12346', 'peer_organization': 'SDWAN-VIPTELA - 249781', 'proxy_state': 'No', 'uptime': '24:22:07:45', 'state': 'up', 'controller_group_id': '0'}, '1.1.1.4': {'peer_type': 'vsmart', 'peer_protocol': 'dtls', 'site_id': '4294950464', 'domain_id': '1', 'peer_private_ip': '10.0.2.163', 'peer_private_port': '12346', 'peer_public_ip': '52.28.233.22', 'peer_public_port': '12346', 'peer_organization': 'SDWAN-VIPTELA - 249781', 'proxy_state': 'No', 'uptime': '17:08:27:45', 'state': 'up', 'controller_group_id': '0'}, '1.1.1.6': {'peer_type': 'vmanage', 'peer_protocol': 'dtls', 'site_id': '4294950465', 'domain_id': '0', 'peer_private_ip': '10.0.2.33', 'peer_private_port': '12746', 'peer_public_ip': '3.123.213.130', 'peer_public_port': '12746', 'peer_organization': 'SDWAN-VIPTELA - 249781', 'proxy_state': 'No', 'uptime': '17:08:28:03', 'state': 'up', 'controller_group_id': '0'}}}}}`
