### ISSUE TITLE
Genie IOS-XE parser "show track" not working for SDWAN

### ISSUE THREAD

**Issue by assadniang** [CiscoTestAutomation/genieparser#807]
The '**show track**' parser is not working for router in SDWAN mode

genie==23.8
pyats==23.8

     C8500L8S4XBR60:
        type: router
        os: iosxe
        platform: sdwan
        #alias: 'uut'
        credentials:
            default:
                username: admin
                password: admin
        connections:
            cli:
                protocol: ssh
                ip: 172.30.7.189
                ssh_options: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

```
from pyats.topology import loader
from unicon.core.errors import TimeoutError, StateMachineError, ConnectionError
import time


testbed = loader.load('/opt/labs-scripts/python/pytest/nfv/suites/cisco/sdwan/tests/testbed_vars/devices.yaml')

device = testbed.devices['C8500L8S4XBR60']

print(f"\n>>> Login to device {device}")

for i in range(5):
    try:
        device.connect()
    except (TimeoutError, StateMachineError, ConnectionError) as error:
        print(f"Attempt {i+1}\nFailed to connect to device {error}")
        print(f"Retrying...")
        time.sleep(30)
    else:
        break
else:
    print(f"All connections attempt to {device['host-name']} failed.")
    
assert device.connected, 'Failed to connect to router'
print(f"Successfully connected to {device}")

output = device.parse('show track')

print(output)
print('**********************')

device.disconnect()
```

Output

```
Smart Licensing Status: Smart Licensing Using Policy

cisco C8500L-8S4X (1RU) processor with 613107K/6147K bytes of memory.
Processor board ID FLX244203G9
Router operating mode: Controller-Managed
8 Gigabit Ethernet interfaces
4 Ten Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
15728640K bytes of physical memory.
15151103K bytes of eUSB flash at bootflash:.
15269887K bytes of USB hard disk at harddisk:.

Configuration register is 0x2102

C8500L8S4XBR60#

2024-01-02 13:40:10,585: %UNICON-INFO: +++ C8500L8S4XBR60 with via 'cli': configure +++
config-transaction

admin connected from 127.0.0.1 using console on C8500L8S4XBR60
C8500L8S4XBR60(config)# no logging console
C8500L8S4XBR60(config)# commit
Aborted: 'system is-vmanaged': This device is being managed by vManage, configuration through CLI is not allowed.
C8500L8S4XBR60(config)# end
Uncommitted changes found, commit them? [yes/no/CANCEL] no
C8500L8S4XBR60#
Successfully connected to Device C8500L8S4XBR60, type router

2024-01-02 13:40:14,288: %UNICON-INFO: +++ C8500L8S4XBR60 with via 'cli': executing command 'show track' +++
show track
Track 1
  Interface GigabitEthernet0/0/0 line-protocol
  Line protocol is Up
    3 changes, last change 00:55:09
  Tracked by:
    Track List 12
Track 2
  Interface GigabitEthernet0/0/1 line-protocol
  Line protocol is Up
    3 changes, last change 00:53:44
  Tracked by:
    Track List 12
Track 12
  List boolean or
  Boolean OR is Up
    4 changes, last change 00:55:09
    object 1 Up
    object 2 Up
  Tracked by:
    VRRPv3 GigabitEthernet0/0/2 IPv4 group 1
C8500L8S4XBR60#
Traceback (most recent call last):
  File "/opt/labs-scripts/python/pytest/nfv/suites/cisco/sdwan/tests/pyats_test.py", line 27, in <module>
    output = device.parse('show track')
  File "src/genie/conf/base/device.py", line 531, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 570, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/conf/base/device.py", line 568, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 308, in genie.metaparser._metaparser.MetaParser.parse
  File "/opt/labs-scripts/python/pytest/nfv/suites/cisco/.venv/lib64/python3.9/site-packages/genie/libs/parser/iosxe/show_track.py", line 152, in cli
    type_dict['state'] = group['state']
UnboundLocalError: local variable 'type_dict' referenced before assignment
```

**Comment by SohanTirpude** [comment]
Hello @assadniang, 

I found the solution for this issue and now this is how the output looks like:

```
{
    "type": {
        "Interface": [
            {
                "name": "GigabitEthernet0/0/0",
                "state": "Up",
                "change_count": 3,
                "last_change": "00:55:09"
            },
            {
                "name": "GigabitEthernet0/0/1",
                "state": "Up",
                "change_count": 3,
                "last_change": "00:53:44"
            }
        ]
    }
}
```

The only issue is with the data of `Tracked by` for both `Track 1` and `Track 2` tracks. Because it is linked to the `Tracked by` of `Track 12`.  I am not sure on how to map it to both tracks. Currently I am looking into it. I will update you soon on this.

Thank you.

**Comment by assadniang** [comment]
@SohanTirpude 
yes, I think that would work

Here is the #sh track output from the device

```
track 1 interface GigabitEthernet0/0/0 line-protocol
!
track 2 interface GigabitEthernet0/0/1 line-protocol
!
track 12 list boolean or
 object 1
 object 2
!
```

```
C8500L8S4XBR60#      sh track 
Track 1
  Interface GigabitEthernet0/0/0 line-protocol
  Line protocol is Up
    1 change, last change 5d00h
  Tracked by:
    Track List 12
Track 2
  Interface GigabitEthernet0/0/1 line-protocol
  Line protocol is Up
    1 change, last change 5d00h
  Tracked by:
    Track List 12
Track 12
  List boolean or
  Boolean OR is Up
    2 changes, last change 5d00h
    object 1 Up
    object 2 Up
  Tracked by:
    VRRPv3 GigabitEthernet0/0/2 IPv4 group 1
```

**Comment by SohanTirpude** [comment]
Hello @assadniang,

One question is what `Track 12` is here? Don't we have to capture that along with `Track 1` and `Track 2`? I think we have to. Also, for `Track 1` and `Track 2`, we have value `Track List 12` for `Tracked by`. So, that means, as per the existing output, do we have to capture this as well?

Kindly let me know.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @assadniang,

Is there any update on this? Kindly let me know.

> Hello @assadniang,
> 
> One question is what `Track 12` is here? Don't we have to capture that along with `Track 1` and `Track 2`? I think we should, right? Also, for `Track 1` and `Track 2`, we have value `Track List 12` for `Tracked by`. So, that means, as per the existing output, do we have to capture this as well?
> 
> Kindly let me know.
> 
> Thank you.

**Comment by SohanTirpude** [comment]
Hello @assadniang,

It seems you are not responding, hence I am closing this ticket. Because we need more information to proceed with the fix, but it is not available for now. In future, if we get the required information, we will proceed with the fix accordingly.

Thank you.
