### ISSUE TITLE
iosxe show cts interface parser doesn't work with port channel interface on Cat 9300

### ISSUE THREAD

**Issue by aj-cruz** [CiscoTestAutomation/genieparser#812]
Switch Model: C9300-48U
OS Version: 17.3.3

Parsing of `show cts interface` results in this raw output:
```
Interface Port-channel22:
    CTS is disabled.

    L3 IPM:   disabled.
```
The Genie parser throws the following exception:
```
  File "/home/aj/projects/python/thr-cts-readiness/.venv/lib/python3.11/site-packages/genie/libs/parser/iosxe/show_cts.py", line 2539, in cli
    intf_dict['l3_ipm'] = l3_ipm
    ^^^^^^^^^
UnboundLocalError: cannot access local variable 'intf_dict' where it is not associated with a value
```

Looking at the code it appears the regex match to create intf_dict is:
`p2 = re.compile(r'^Interface\s+(?P<interface>\S+\d+\/\d+\/\d+|Tunnel\d+|\S+\d+\/\d+\/\d+\.\d+):')`

It seems to me like that should match the Port-channel interface, but maybe it's not?

**Comment by aj-cruz** [comment]
I confirmed the regex does not match that line in Python 3.11.7:
```
import re

p2 = re.compile(r'^Interface\s+(?P<interface>\S+\d+\/\d+\/\d+|Tunnel\d+|\S+\d+\/\d+\/\d+\.\d+):')
line = "Interface Port-channel22:"
m = p2.match(line)

print(type(m))
<class 'NoneType'>
```

**Comment by SohanTirpude** [comment]
Hello @aj-cruz,

Thank you for letting us know this issue. It seems that you have the solution as well for this issue. So, would you like to raise a PR and get it fixed? Or if not, then let me know.

Anyway, I will propose a slight change in the fix. I will take out the `\d+` separately and keep `Tunnel` and `Port-channel` in group like this: `(Tunnel|Port-channel)\d+`

The complete regex will be like this:

```
^Interface\s+(?P<interface>\S+\d+\/\d+\/\d+|(Tunnel|Port-channel)\d+|\S+\d+\/\d+\/\d+\.\d+):
```

Kindly let me know you interest in getting this issue fixed. 

Thank you.

**Comment by SohanTirpude** [comment]
Hello @aj-cruz,

Thank you for letting us know about this issue. It seems you have fix for this issue already. So, would you like to contribute to the genieparser repo? 

Also, it seems you'll have to make few changes as well considering the schema we have. You'll have to make changes to regex `p3` as well to get `CTC` status value, as well as you'll have to make `global_dot1x_feature` optional because it is mandatory now and your raw output does not have it.

So, if you are interested then kindly consider above changes while raising PR. Even if you are not interested, no issue, just let me know.

Thank you.

**Comment by aj-cruz** [comment]
Ya I'll take a closer look considering the things you mentioned and put together a PR.
Thanks.

**Comment by aj-cruz** [comment]
@SohanTirpude Well maybe I better leave it to the professionals.
I change the Schema to:
```python
    schema = {
        Optional('global_dot1x_feature'): str,
        'interfaces': {
            Any(): {
                'cts': {
                    'cts_status': str,
                    Optional('mode'): str
                },
                Optional('ifc_state'): str,
                Optional('intf_active_for'): str,
                Optional('authentication'): {
                    'status': str,
                    Optional('peer_identity'): str,
                    Optional('peer_advertised_capabilities'): str
                },
                Optional('authorization'): {
                    'status': str,
                    Optional('peer_sgt'): int,
                    Optional('peer_sgt_assignment'): str
                },
                Optional('sap_status'): str,
                Optional('propagate_sgt'): str,
                Optional('cache_info'): {
                    'expiration': str,
                    'cache_applied_to_link': str
                },
                Optional('statistics'): {
                    'authc_success': int,
                    'authc_reject': int,
                    'authc_failure': int,
                    'authc_no_response': int,
                    'authc_logoff': int,
                    'sap_success': int,
                    'sap_fail': int,
                    'authz_success': int,
                    'authz_fail': int,
                    'port_auth_fail': int
                },
                'l3_ipm': str
            },
        }
    }
```

Then I changed the two regex patterns to:
```python
p2 = re.compile(r'^Interface\s+(?P<interface>\S+\d+\/\d+\/\d+|(Tunnel|Port-channel)\d+|\S+\d+\/\d+\/\d+\.\d+):')
p3 = re.compile(r'^CTS\s+is\s+(?P<cts_status>\S+)(\.|,\s+mode:\s+(?P<mode>\S+))')
```
When I do this the Actions Folder Based Testing fails complaining that the schema cts.mode value is None but str required.  
I tried changing that to `Optional('mode'): Optional(str)` but I get this error now:
```
2024-01-26T01:34:14: %SCRIPT-ERROR: Traceback (most recent call last):
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 318, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 288, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 390, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 363, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 318, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 288, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 390, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 363, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 248, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 256, in genie.metaparser.util.schemaengine.Schema.validate
2024-01-26T01:34:14: %SCRIPT-ERROR: genie.metaparser.util.exceptions.SchemaTypeError: Expected type '<class 'str'>' but got type 'None'(<class 'NoneType'>)
2024-01-26T01:34:14: %SCRIPT-ERROR: 
2024-01-26T01:34:14: %SCRIPT-ERROR: The above exception was the direct cause of the following exception:
2024-01-26T01:34:14: %SCRIPT-ERROR: 
2024-01-26T01:34:14: %SCRIPT-ERROR: Traceback (most recent call last):
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "/home/runner/work/genieparser/genieparser/src/genie/libs/parser/utils/unittests.py", line 575, in test_golden
2024-01-26T01:34:14: %SCRIPT-ERROR:     parsed_output = obj.parse(**arguments)
2024-01-26T01:34:14: %SCRIPT-ERROR:   File "src/genie/metaparser/_metaparser.py", line 345, in genie.metaparser._metaparser.MetaParser.parse
2024-01-26T01:34:14: %SCRIPT-ERROR: Exception: Parser ShowCtsInterface schema checking failed
```
I'm not smart enough to know where to go from there.

**Comment by aj-cruz** [comment]
Side note, I noticed golden_output2_output.txt has port-channels in the raw output but golden_output2_expected.py has no expected output for them. I went ahead and added them.

I can't tell from that traceback which key has a value of type None so I took the raw output and ran it through the parser with my fixes.
It generates the output no problems. I don't see any values set to None in the output other than the cts mode of the Port-channels.
I then loaded the outputs into python and did a comparison and there is no difference. The dictionary from the golden_output2_expected.py matches exactly the dictionary I get when I manually parse the raw output.

I'm guessing it has to do with the schema.  
I notice no other schemas have optional values so I'm not sure if Optional() from genie.metaparser.util.schemaengine works for keys?

I don't know what I'm doing :D

**Comment by aj-cruz** [comment]
er wait, given the raw port-channel output, I think the mode key shoudn't even be in the output.
Which means my p3 regex pattern is wrong. I'll investigate...

**Comment by aj-cruz** [comment]
I see in the p3.match() logic where the mode key is generated. I put a conditional in there and now the GH Actions tests are passing. I'll put together a PR

**Comment by SohanTirpude** [comment]
Hello @aj-cruz,

Glad to hear that you were able to resolve the issue by yourself. Kindly make sure to follow these guidelines while raising PR: https://github.com/CiscoTestAutomation/genieparser#to-contributors.

**Comment by aj-cruz** [comment]
Hi @SohanTirpude 
I'm new to all this, when I do the PR, what's the proper base branch to use?

**Comment by aj-cruz** [comment]
nevermind that, looking at all the PRs I see they're using master. I'll do the same thanks!

**Comment by SohanTirpude** [comment]
Hello @aj-cruz,

I just checked your PR, so far it looks good. The only thing is you'll have to add new golden_output files for your change.

**Comment by aj-cruz** [comment]
@SohanTirpude 
golden_output2_output.txt already had Port-channel interfaces in the raw output so I didn't add anything new there.
Although the port-channels were in the raw output for golden_output2, golden_output2_expected.py didn't have anything for the port-channel interfaces, so I modified that file to include them.

Is that sufficient or do I need to add brand new golden_output files instead?

**Comment by SohanTirpude** [comment]
Hello @aj-cruz,

Yes, you will have to new golden_output files, because this is what the reviewers' will demand later.

**Comment by aj-cruz** [comment]
@SohanTirpude Done

**Comment by SohanTirpude** [comment]
Hello @aj-cruz, 

I have just checked your PR and it seems you removed the output from golden_output2_output.txt file. Please revert it back.

**Comment by SohanTirpude** [comment]
Hello @aj-cruz,

You PR got merged so in the upcoming pyATS version i.e. 24.2 this fix will be available. Hence, kindly re-check with newer pyATS version.

Thank you.
