### ISSUE TITLE
error when using markup to parse non-tabular text

### ISSUE THREAD

**Issue by daviddayong** [CiscoTestAutomation/genieparser#830]
Support team,
I encountered error when using markup to parse non-tabular text, detailed error message show as below, and script/testbed as enclosed.
Please help to investigate and advise how to fix that. Thanks very much.

root@1c0d25084801:/pyats/mock# /pyats/bin/python parser1.py

2024-03-13 06:52:06,168: %UNICON-INFO: +++ dev1 logfile /tmp/dev1-cli-20240313T065206167.log +++

2024-03-13 06:52:06,168: %UNICON-INFO: +++ Unicon plugin linux (unicon.plugins.linux) +++

2024-03-13 06:52:06,172: %UNICON-INFO: +++ connection to spawn: ssh -l agent 10.61.73.183, id: 140667377989664 +++

2024-03-13 06:52:06,173: %UNICON-INFO: connection to dev1
[agent@10.61.73.183's](mailto:agent@10.61.73.183's) password:
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 6.2.0-39-generic x86_64)

* Documentation:  https://help.ubuntu.com/
* Management:     https://landscape.canonical.com/
* Support:        https://ubuntu.com/advantage

221 updates can be applied immediately.
2 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

1 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log
*** System restart required ***
Last login: Wed Mar 13 14:39:44 2024 from 172.17.0.2
agent@agent-virtual-machine:~$

2024-03-13 06:52:06,479: %UNICON-INFO: +++ initializing handle +++
uut.os.1===linux
Traceback (most recent call last):
  File "/pyats/mock/parser1.py", line 37, in <module>
    pgfill = parsergen.oper_fill(device=uut,show_command=('ifconfig', [], {'ifname':'docker0'}),attrvalpairs=attrValPairsToCheck,
  File "src/genie/parsergen/_parsergen.py", line 570, in genie.parsergen._parsergen.oper_fill.__init__
KeyError: 'linux'
root@1c0d25084801:/pyats/mock#
[script_and_testbed.zip](https://github.com/CiscoTestAutomation/genieparser/files/14644309/script_and_testbed.zip)

**Comment by ParimiNeeraja** [comment]
Hello daviddayong,

Kindly give me some time, will check and update you.

**Comment by Neeraja1bala** [comment]
Hello @daviddayong ,

Can you please share whole output of `ifconfig` command.

**Comment by Neeraja1bala** [comment]
Hello @daviddayong ,

Could you please share the output of that command.

**Comment by Neeraja1bala** [comment]
Hello @daviddayong ,

Any update on this issue. Kindly let us know the update

**Comment by Neeraja1bala** [comment]
As we haven't heard back from you , we will be closing this ticket.
If you still facing this issue please feel free to reopen with output of `ifconfig `command.

Thanks
