### ISSUE TITLE
[IOS-XE] Parser for "show isis node level-1" does not work

### ISSUE THREAD

**Issue by ChristopherJHart** [CiscoTestAutomation/genieparser#846]
The parser for IOS-XE's `show isis node level-1` command does not work.

Sample CLI output:
```
R1#show isis node level-1 

Tag 64512:

ISIS level-1 node information for R1.00
  IP router ID: 192.0.2.53 (LSP #0)
  IP interface address: 192.0.2.53 (LSP #0)
  IP PQ address: 192.0.2.53
  IP prefix SID: 990, R:0 N:1 P:0 E:0 V:0 L:0
  IP strict-SPF SID: 991, R:0 N:1 P:0 E:0 V:0 L:0
  LSP index: 1
  SRGB start[0]: 16000, SRGB range[0]: 8000 (LSP #0)
  SRLB start[0]: 15000, SRLB range[0]: 1000 (LSP #0)
  SR capable: Yes, Strict-SPF capable: Yes (LSP #0)
  SR Flex Algorithm 129,130,139,140,149,150
  Flex algorithm:129 Metric-Type:IGP Alg-type:SPF Priority:128
    Affinity Include-any:
       0x00000004 
  Flex algorithm:130 Metric-Type:IGP Alg-type:SPF Priority:128
    Affinity Include-any:
       0x00000002 
  Flex algorithm:139 Metric-Type:IGP Alg-type:SPF Priority:128
    Affinity Include-all:
       0x0000000C 
  Flex algorithm:140 Metric-Type:IGP Alg-type:SPF Priority:128
    Affinity Include-all:
       0x0000000A 
  Flex algorithm:149 Metric-Type:IGP Alg-type:SPF Priority:128
    Affinity Include-all:
       0x00000014 
  Flex algorithm:150 Metric-Type:IGP Alg-type:SPF Priority:128
    Affinity Include-all:
       0x00000012 

```
Traceback:
```
2024-04-29T12:36:48: %SCRIPT-ERROR: Traceback (most recent call last):
2024-04-29T12:36:48: %SCRIPT-ERROR:   File "/Users/chart2/Documents/Python/genieparser/src/genie/libs/parser/utils/unittests.py", line 580, in test_golden
2024-04-29T12:36:48: %SCRIPT-ERROR:     parsed_output = obj.parse(**arguments)
2024-04-29T12:36:48: %SCRIPT-ERROR:                     ^^^^^^^^^^^^^^^^^^^^^^
2024-04-29T12:36:48: %SCRIPT-ERROR:   File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
2024-04-29T12:36:48: %SCRIPT-ERROR:   File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
2024-04-29T12:36:48: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
2024-04-29T12:36:48: %SCRIPT-ERROR: genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['tag', '64512', 'level', 'level-1', 'host', 'R1.00', 'lsp_index', 1, 'sr_capable'], ['tag', '64512', 'level', 'level-1', 'host', 'R1.00', 'lsp_index', 1, 'strict_spf_capable']]
```

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

It looks like a bug. Kindly give me some time to analyse this issue.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

I have made required changes and now the output looks like this:
```
{
    "tag": {
        "64512": {
            "level": {
                "level-1": {
                    "host": {
                        "R1.00": {
                            "ip_interface_address": "192.0.2.53",
                            "lsp_id": 0,
                            "lsp_index": {
                                1: {
                                    "sr_capable": "Yes",
                                    "strict_spf_capable": "Yes"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
But in your raw output, I am seeing lot of details which are not getting parsed in this parser. Kindly let me know if you want to parse those missing details as well. If yes then kindly share which data you want to parse.

Thank you.

**Comment by ChristopherJHart** [comment]
Hi @SohanTirpude - ideally, we'd like all of the information present in the output to be parsed as well. We are writing automated tests based upon each key/value pair in Genie parsers, so the more information we can fit into the parsed output, the better.

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

I have updated the parser to parse all possible values from the command output and this is how the expected output looks like:
```
{
    "tag": {
        "64512": {
            "level": {
                "level-1": {
                    "host": {
                        "R1.00": {
                            "ip_router_id": "192.0.2.53",
                            "ip_router_lsp_id": 0,
                            "ip_interface_address": "192.0.2.53",
                            "lsp_id": 0,
                            "ip_pq_address": "192.0.2.53",
                            "ip_prefix": {
                                "sid": 990,
                                "r_flag": 0,
                                "n_flag": 1,
                                "p_flag": 0,
                                "e_flag": 0,
                                "v_flag": 0,
                                "l_flag": 0
                            },
                            "ip_strict_spf": {
                                "sid": 990,
                                "r_flag": 0,
                                "n_flag": 1,
                                "p_flag": 0,
                                "e_flag": 0,
                                "v_flag": 0,
                                "l_flag": 0
                            },
                            "lsp_index": {
                                1: {
                                    "sr_capable": "Yes",
                                    "strict_spf_capable": "Yes"
                                }
                            },
                            "srgb": {
                                "start": 16000,
                                "range": 8000,
                                "lsp_id": 0
                            },
                            "srlb": {
                                "start": 15000,
                                "range": 1000,
                                "lsp_id": 0
                            },
                            "flex_algo": {
                                "129": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-any": [
                                            "0x00000004"
                                        ]
                                    }
                                },
                                "130": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-any": [
                                            "0x00000002"
                                        ]
                                    }
                                },
                                "139": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": []
                                    }
                                },
                                "140": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": []
                                    }
                                },
                                "149": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": [
                                            "0x00000014"
                                        ]
                                    }
                                },
                                "150": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": [
                                            "0x00000012"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
Kindly verify.

Thank you.

**Comment by ChristopherJHart** [comment]
@SohanTirpude The schema looks good. Is the value for `Include-all` supposed to be an empty list for some flex algos?

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

This is how the updated output looks like:
```
{
    "tag": {
        "64512": {
            "level": {
                "level-1": {
                    "host": {
                        "R1.00": {
                            "ip_router_id": "192.0.2.53",
                            "ip_router_lsp_id": 0,
                            "ip_interface_address": "192.0.2.53",
                            "lsp_id": 0,
                            "ip_pq_address": "192.0.2.53",
                            "ip_prefix": {
                                "sid": 990,
                                "r_flag": 0,
                                "n_flag": 1,
                                "p_flag": 0,
                                "e_flag": 0,
                                "v_flag": 0,
                                "l_flag": 0
                            },
                            "ip_strict_spf": {
                                "sid": 990,
                                "r_flag": 0,
                                "n_flag": 1,
                                "p_flag": 0,
                                "e_flag": 0,
                                "v_flag": 0,
                                "l_flag": 0
                            },
                            "lsp_index": {
                                1: {
                                    "sr_capable": "Yes",
                                    "strict_spf_capable": "Yes"
                                }
                            },
                            "srgb": {
                                "start": 16000,
                                "range": 8000,
                                "lsp_id": 0
                            },
                            "srlb": {
                                "start": 15000,
                                "range": 1000,
                                "lsp_id": 0
                            },
                            "flex_algo": {
                                "129": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-any": [
                                            "0x00000004"
                                        ]
                                    }
                                },
                                "130": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-any": [
                                            "0x00000002"
                                        ]
                                    }
                                },
                                "139": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": [
                                            "0x0000000C"
                                        ]
                                    }
                                },
                                "140": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": [
                                            "0x0000000A"
                                        ]
                                    }
                                },
                                "149": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": [
                                            "0x00000014"
                                        ]
                                    }
                                },
                                "150": {
                                    "metric_type": "IGP",
                                    "alg_type": "SPF",
                                    "priority": 128,
                                    "affinity": {
                                        "Include-all": [
                                            "0x00000012"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by ChristopherJHart** [comment]
@SohanTirpude That looks good - thank you!

**Comment by SohanTirpude** [comment]
Hello @ChristopherJHart,

The PR got merged and the fix will be available in the upcoming release. Hence, I am closing this ticket for now. Kindly recheck with new pyats version.

Thank you.
