### ISSUE TITLE
[IOS-XE] Parser for "show mka policy" does not work

### ISSUE THREAD

**Issue by ChristopherJHart** [CiscoTestAutomation/genieparser#850]
Sample CLI output:
```
MKA Policy Summary...

Codes : CO - Confidentiality Offset, ICVIND - Include ICV-Indicator,
        SAKR OLPL - SAK-Rekey On-Live-Peer-Loss,
        DP - Delay Protect, KS Prio - Key Server Priority

Policy            KS   DP    CO SAKR  ICVIND Cipher          Interfaces        
Name              Prio          OLPL         Suite(s)        Applied           
===============================================================================
*DEFAULT POLICY*  0    FALSE 0  FALSE TRUE   GCM-AES-128     
                                             GCM-AES-256     

MACSEC_POLICY_1   0    FALSE 0  FALSE TRUE   GCM-AES-256     Te0/0/0    Te0/0/1   
```
Traceback:
```
2024-04-29T13:10:35: %SCRIPT-ERROR: Traceback (most recent call last):
2024-04-29T13:10:35: %SCRIPT-ERROR:   File "/Users/chart2/Documents/Python/genieparser/src/genie/libs/parser/utils/unittests.py", line 580, in test_golden
2024-04-29T13:10:35: %SCRIPT-ERROR:     parsed_output = obj.parse(**arguments)
2024-04-29T13:10:35: %SCRIPT-ERROR:                     ^^^^^^^^^^^^^^^^^^^^^^
2024-04-29T13:10:35: %SCRIPT-ERROR:   File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
2024-04-29T13:10:35: %SCRIPT-ERROR:   File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
2024-04-29T13:10:35: %SCRIPT-ERROR:   File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
2024-04-29T13:10:35: %SCRIPT-ERROR: genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['send_secure_announcements']]
```

**Comment by Harishv01** [comment]
```
expected_output = {
    "policy": {
        "MACSEC_POLICY_1": {
            "key_server_priority": 0,
            "delay_protect": "FALSE",
            "confidentiality_offset": 0,
            "sak_rey_key_on_live_peer_loss": "FALSE",
            "include_icv_indicator": "TRUE",
            "cipher": "GCM-AES-256",
            "interfaces": [
                "Te0/0/0",
                "Te0/0/1"
            ]
        }
    }
}
```

I have raised a PR for your issue and the output looks like the above. Please check and let me know in case of any queries. If everything is good, I will merge the PR.

**Comment by ChristopherJHart** [comment]
Hi @Harishv01 - that looks good to me! Should the interface names be expanded?

**Comment by Harishv01** [comment]
Sorry,It is not possible to change the interface names because many other outputs also rely on it. Because of that, it is not possible. 

Thank you.

**Comment by Harishv01** [comment]
The PR has been merged and this fix will be available in the next version of pyats, i.e. 24.5. Hence, I am closing this ticket.

Thank you.
