### ISSUE TITLE
[IOS-XE]parse 'show ip nbar protocol-discovery protocol' fail

### ISSUE THREAD

**Issue by hsang88** [CiscoTestAutomation/genieparser#914]
parse report fail if the interface is vlan, please check below log, interface has other types, such as TwoGigabitEthernet0/0/7 ...

```
show ip nbar protocol-discovery protocol

 Vlan150

 Last clearing of "show ip nbar protocol-discovery" counters 00:00:31


                                  Input                    Output
                                  -----                    ------
 Protocol                         Packet Count             Packet Count
                                  Byte Count               Byte Count
                                  5min Bit Rate (bps)      5min Bit Rate (bps)
                                  5min Max Bit Rate (bps)  5min Max Bit Rate (bps)
 -------------------------------- ------------------------ ------------------------
 ipv6-icmp                        1011                     1005
                                  115034                   114458
                                  6000                     6000
                                  6000                     6000
 ping                             999                      999
                                  113886                   113886
                                  3000                     3000
                                  6000                     6000
 Total                            2010                     2004
                                  228920                   228344
                                  9000                     9000
                                  12000                    12000

Traceback (most recent call last):
File "/users/hsang/backup/svi/testcases/a88.py", line 480, in svi_avc
parsed = uut1.parse('show ip nbar protocol-discovery protocol')
    File "/nobackup/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/conf/base/device.py", line 535, in parse
      return self._get_parser_output(kwargs, parsers[0], parsers[1],
    File "/nobackup/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/conf/base/device.py", line 572, in _get_parser_output
      out = parser_instance.parse(**copy)
    File "/nobackup/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/metaparser/_metaparser.py", line 308, in parse
      output = call(**kwargs)
    File "/nobackup/hsang/workspace/polaris/binos/linkfarm/sdks-host/iosxe-pyats/nativesdk/sdk/sysroots/x86_64-xesdk-linux/usr/lib/python3.10/site-packages/genie/libs/parser/iosxe/show_nbar.py", line 83, in cli
      interface['protocol'][protocol]={}
  UnboundLocalError: local variable 'interface' referenced before assignment
```
it behave normally if interface start with Gi,

```
show ip nbar protocol-discovery protocol

 GigabitEthernet0/1/3 

 Last clearing of "show ip nbar protocol-discovery" counters 00:09:36


                                  Input                    Output                  
                                  -----                    ------                  
 Protocol                         Packet Count             Packet Count            
                                  Byte Count               Byte Count              
                                  5min Bit Rate (bps)      5min Bit Rate (bps)     
                                  5min Max Bit Rate (bps)  5min Max Bit Rate (bps) 
 -------------------------------- ------------------------ ------------------------
 ping                             999                      999                     
                                  113886                   113886                  
                                  0                        0                       
                                  6000                     6000                    
 Total                            999                      999                     
                                  113886                   113886                  
                                  0                        0                       
                                  6000                     6000                    
Charon-037-4P#
>>> import pprint
>>> pprint.pprint(parsed)
{'interface': {'GigabitEthernet0/1/3': {'protocol': {'Total': {'in_5min_bit_rate_bps': 6000,
                                                               'in_5min_max_bit_rate_bps': 6000,
                                                               'in_byte_count': 6000,
                                                               'in_packet_count': 999,
                                                               'out_5min_bit_rate_bps': 6000,
                                                               'out_5min_max_bit_rate_bps': 6000,
                                                               'out_byte_count': 6000,
                                                               'out_packet_count': 999},
                                                     'ping': {'in_5min_bit_rate_bps': 6000,
                                                              'in_5min_max_bit_rate_bps': 6000,
                                                              'in_byte_count': 6000,
                                                              'in_packet_count': 999,
                                                              'out_5min_bit_rate_bps': 6000,
                                                              'out_5min_max_bit_rate_bps': 6000,
                                                              'out_byte_count': 6000,
                                                              'out_packet_count': 999}}}}}
```

**Comment by ParimiNeeraja** [comment]
Hello @hsang88 

Could you please check the below expected output looks finr or not. 

Thank you!

```
{
    "interface": {
        "Vlan150": {
            "protocol": {
                "ipv6-icmp": {
                    "in_packet_count": 1011,
                    "out_packet_count": 1005,
                    "in_byte_count": 6000,
                    "out_byte_count": 6000,
                    "in_5min_bit_rate_bps": 6000,
                    "out_5min_bit_rate_bps": 6000,
                    "in_5min_max_bit_rate_bps": 6000,
                    "out_5min_max_bit_rate_bps": 6000
                },
                "ping": {
                    "in_packet_count": 999,
                    "out_packet_count": 999,
                    "in_byte_count": 6000,
                    "out_byte_count": 6000,
                    "in_5min_bit_rate_bps": 6000,
                    "out_5min_bit_rate_bps": 6000,
                    "in_5min_max_bit_rate_bps": 6000,
                    "out_5min_max_bit_rate_bps": 6000
                },
                "Total": {
                    "in_packet_count": 2010,
                    "out_packet_count": 2004,
                    "in_byte_count": 12000,
                    "out_byte_count": 12000,
                    "in_5min_bit_rate_bps": 12000,
                    "out_5min_bit_rate_bps": 12000,
                    "in_5min_max_bit_rate_bps": 12000,
                    "out_5min_max_bit_rate_bps": 12000
                }
            }
        }
    }
}
```

**Comment by hsang88** [comment]
Yes, this is fine. thanks.

**Comment by ParimiNeeraja** [comment]
Hello,

The PR has been merged and the fix will be available in the next version. Hence, will be closing the ticket.
